### ISSUE TITLE
Group/Association nomenclature

### ISSUE THREAD

**Issue by Tilix4** [mltframework/mlt#375] opened 2018-10-18 08:58 UTC
It would be great to implement a group/association nomenclature to signify producers are grouped together even if they are not in the same track or playlist.  
For example, I want to synchronize video and audio not recorded together. I associate them in an editing software and the editor wants to edit on another MLT based software, I don't have to do everything again.

**Comment by Tilix4** [comment] 2018-10-18 21:02
"Nested sequence" is not what I'm looking for, because in practice it means these clips/producers are one after the other, if visualy they are into another sequence.
What I meant, is more about grouping, you group clips with other ones, in the same timeline, and when you select one, every clip in this group is selected too, when you move one, they move together.
It could be useful to add and effect to each clip of a group even if they are separated by 10 minutes, with some "Add effect to every element of group".
My example about synchronized video and sound works well too. If I want to keep sounds in sound tracks and video in video tracks, but they are associated, they'll move together. And if at a moment I want to dissociate it's quick and easy. "Nested sequences" less easy to manage because you don't see exactly what's inside... I don't if I'm clear enough, it's more about editing habits and behaviors I see in productions.

About the MLT XML adapter, I heard about this one : https://github.com/apetrynet/OpenTimelineIO/blob/mlt_xml_adapter/opentimelineio_contrib/adapters/mlt_xml.py
It's not done for now, and I discussed with the author and he told me he needs this kind of group feature. (https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/343#issuecomment-430930368)

**Comment by ddennedy** [comment] 2018-10-18 21:46
I understand. I tend to think what you are describing is more a function of a UI, but it can certainly be nice to save this information into the project file. When I have thought about adding something like this to Shotcut, I planned to do it through some extension to the project file that MLT does not know or care about. However, that approach would not automate the idea of a filter applied to every clip in the group without opening it in Shotcut, which would apply every change to every clip in the group. So, yes, there is an advantage to the idea of managing it within MLT.

However, growing the framework part of MLT at this time is a very low priority for me at this time. There is more work about certain functions of certain modules or adding new modules. Basically, Shotcut is driving MLT development for me in the near term; however, I do expect to add multiple selection and grouping to Shotcut at some point in 2019. Meanwhile, there is still much of current MLT to expose through Shotcut before getting to that. I think the same philosophy should apply to the OpenTimelineIO adapter: Get things that already exist today working good before trying to add more things that will take awhile to stabilize.

I generally do not take feature requests and keep feature request issues open in GitHub Issues tracker, but I will for now while having a discussion and thinking about this further.

**Comment by Tilix4** [comment] 2018-10-18 22:11
Thank you for taking this into consideration. Tell me if I can help in any way.
If you need some more information or case studies feel free to ask.

**Comment by ddennedy** [comment] 2019-02-02 02:11
Closing as not a bug and feature requests without code (i.e. pull requested) are not accepted.

**Closed by ddennedy** 2019-02-02 02:11 UTC
