### ISSUE TITLE
Is that possible to use a producer as a filter's resource?

### ISSUE THREAD

**Issue by hpp0hpp** [mltframework/mlt#628] opened 2020-12-06 12:11 UTC
Some filter needs a resource, such as luma, which accept a existing luma map, but sometimes I need to  apply some other filter on the luma map file before I use that. So I am thinking is that possible to use a producer as a filter's resource?

Thank you.

**Comment by bmatherly** [comment] 2020-12-06 13:16
The documentation for the luma filter is here:
https://mltframework.org/plugins/FilterLuma/

You can not use a producer as a luma map. You can, however, create your own luma file. In fact, the filter can use any image file as the luma map. So you can modify it using your favorite graphics editor.

We reserve this issue tracker for bugs and this is not a bug so I will close this.

**Closed by bmatherly** 2020-12-06 13:16 UTC

**Comment by hpp0hpp** [comment] 2020-12-06 15:16
@bmatherly 
Hi, for luma it seems alright, but for mask:From_file in shotcut, or mask_start with shape filtet in melt comandline, some times I want to speed up my matte transition clip, so I have to edit the transition clip first to speed up and export for use. 
if we can use a producer to be a resource of filter, sometimes it will be more handy in lots of cases. I don't need to edit the resource  before I can use it.

Sure I can do that with two times edit, just thought the posibility because mlt is such a flexible edit tool and briliant framework design, that is why I expect more.

**Comment by ddennedy** [comment] 2020-12-06 16:58
You can try using a MLT XML file as resource. Please make sure it is using the same profile.
