### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kulame** [mltframework/mlt#722] opened 2021-07-02 07:16 UTC
i try to build the mlt

cmake --build . 

/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp: In member function ‘virtual unsigned int RtApiOss::getDeviceCount()’:
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8624:3: error: ‘oss_sysinfo’ was not declared in this scope
 8624 |   oss_sysinfo sysinfo;
      |   ^~~~~~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8625:24: error: ‘SNDCTL_SYSINFO’ was not declared in this scope; did you mean ‘SNDCTL_SYNTH_INFO’?
 8625 |   if ( ioctl( mixerfd, SNDCTL_SYSINFO, &sysinfo ) == -1 ) {
      |                        ^~~~~~~~~~~~~~
      |                        SNDCTL_SYNTH_INFO
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8625:41: error: ‘sysinfo’ was not declared in this scope
 8625 |   if ( ioctl( mixerfd, SNDCTL_SYSINFO, &sysinfo ) == -1 ) {
      |                                         ^~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8633:10: error: ‘sysinfo’ was not declared in this scope
 8633 |   return sysinfo.numaudios;
      |          ^~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp: In member function ‘virtual RtAudio::DeviceInfo RtApiOss::getDeviceInfo(unsigned int)’:
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8648:3: error: ‘oss_sysinfo’ was not declared in this scope
 8648 |   oss_sysinfo sysinfo;
      |   ^~~~~~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8649:32: error: ‘SNDCTL_SYSINFO’ was not declared in this scope; did you mean ‘SNDCTL_SYNTH_INFO’?
 8649 |   int result = ioctl( mixerfd, SNDCTL_SYSINFO, &sysinfo );
      |                                ^~~~~~~~~~~~~~
      |                                SNDCTL_SYNTH_INFO
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8649:49: error: ‘sysinfo’ was not declared in this scope
 8649 |   int result = ioctl( mixerfd, SNDCTL_SYSINFO, &sysinfo );
      |                                                 ^~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8672:3: error: ‘oss_audioinfo’ was not declared in this scope
 8672 |   oss_audioinfo ainfo;
      |   ^~~~~~~~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8673:3: error: ‘ainfo’ was not declared in this scope; did you mean ‘info’?
 8673 |   ainfo.dev = device;
      |   ^~~~~
      |   info
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8674:28: error: ‘SNDCTL_AUDIOINFO’ was not declared in this scope; did you mean ‘SNDCTL_MIDI_INFO’?
 8674 |   result = ioctl( mixerfd, SNDCTL_AUDIOINFO, &ainfo );
      |                            ^~~~~~~~~~~~~~~~
      |                            SNDCTL_MIDI_INFO
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8684:21: error: ‘PCM_CAP_OUTPUT’ was not declared in this scope; did you mean ‘PCM_ENABLE_OUTPUT’?
 8684 |   if ( ainfo.caps & PCM_CAP_OUTPUT ) info.outputChannels = ainfo.max_channels;
      |                     ^~~~~~~~~~~~~~
      |                     PCM_ENABLE_OUTPUT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8685:21: error: ‘PCM_CAP_INPUT’ was not declared in this scope; did you mean ‘SYNTH_CAP_INPUT’?
 8685 |   if ( ainfo.caps & PCM_CAP_INPUT ) info.inputChannels = ainfo.max_channels;
      |                     ^~~~~~~~~~~~~
      |                     SYNTH_CAP_INPUT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8686:21: error: ‘PCM_CAP_DUPLEX’ was not declared in this scope; did you mean ‘DSP_CAP_DUPLEX’?
 8686 |   if ( ainfo.caps & PCM_CAP_DUPLEX ) {
      |                     ^~~~~~~~~~~~~~
      |                     DSP_CAP_DUPLEX
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8697:15: error: ‘AFMT_S32_LE’ was not declared in this scope; did you mean ‘AFMT_S16_LE’?
 8697 |   if ( mask & AFMT_S32_LE || mask & AFMT_S32_BE )
      |               ^~~~~~~~~~~
      |               AFMT_S16_LE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8697:37: error: ‘AFMT_S32_BE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8697 |   if ( mask & AFMT_S32_LE || mask & AFMT_S32_BE )
      |                                     ^~~~~~~~~~~
      |                                     AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8699:15: error: ‘AFMT_FLOAT’ was not declared in this scope
 8699 |   if ( mask & AFMT_FLOAT )
      |               ^~~~~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8701:15: error: ‘AFMT_S24_LE’ was not declared in this scope; did you mean ‘AFMT_S16_LE’?
 8701 |   if ( mask & AFMT_S24_LE || mask & AFMT_S24_BE )
      |               ^~~~~~~~~~~
      |               AFMT_S16_LE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8701:37: error: ‘AFMT_S24_BE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8701 |   if ( mask & AFMT_S24_LE || mask & AFMT_S24_BE )
      |                                     ^~~~~~~~~~~
      |                                     AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp: In member function ‘virtual bool RtApiOss::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, RtAudioFormat, unsigned int*, RtAudio::StreamOptions*)’:
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8765:3: error: ‘oss_sysinfo’ was not declared in this scope
 8765 |   oss_sysinfo sysinfo;
      |   ^~~~~~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8766:32: error: ‘SNDCTL_SYSINFO’ was not declared in this scope; did you mean ‘SNDCTL_SYNTH_INFO’?
 8766 |   int result = ioctl( mixerfd, SNDCTL_SYSINFO, &sysinfo );
      |                                ^~~~~~~~~~~~~~
      |                                SNDCTL_SYNTH_INFO
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8766:49: error: ‘sysinfo’ was not declared in this scope
 8766 |   int result = ioctl( mixerfd, SNDCTL_SYSINFO, &sysinfo );
      |                                                 ^~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8788:3: error: ‘oss_audioinfo’ was not declared in this scope
 8788 |   oss_audioinfo ainfo;
      |   ^~~~~~~~~~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8789:3: error: ‘ainfo’ was not declared in this scope
 8789 |   ainfo.dev = device;
      |   ^~~~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8790:28: error: ‘SNDCTL_AUDIOINFO’ was not declared in this scope; did you mean ‘SNDCTL_MIDI_INFO’?
 8790 |   result = ioctl( mixerfd, SNDCTL_AUDIOINFO, &ainfo );
      |                            ^~~~~~~~~~~~~~~~
      |                            SNDCTL_MIDI_INFO
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8799:44: error: ‘PCM_CAP_OUTPUT’ was not declared in this scope; did you mean ‘PCM_ENABLE_OUTPUT’?
 8799 |   if ( ( mode == OUTPUT && !( ainfo.caps & PCM_CAP_OUTPUT ) ) ||
      |                                            ^~~~~~~~~~~~~~
      |                                            PCM_ENABLE_OUTPUT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8800:43: error: ‘PCM_CAP_INPUT’ was not declared in this scope; did you mean ‘SYNTH_CAP_INPUT’?
 8800 |        ( mode == INPUT && !( ainfo.caps & PCM_CAP_INPUT ) ) ) {
      |                                           ^~~~~~~~~~~~~
      |                                           SYNTH_CAP_INPUT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8818:28: error: ‘PCM_CAP_DUPLEX’ was not declared in this scope; did you mean ‘DSP_CAP_DUPLEX’?
 8818 |       if ( !( ainfo.caps & PCM_CAP_DUPLEX ) ) {
      |                            ^~~~~~~~~~~~~~
      |                            DSP_CAP_DUPLEX
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8907:22: error: ‘AFMT_S16_OE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8907 |     else if ( mask & AFMT_S16_OE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8914:17: error: ‘AFMT_S24_NE’ was not declared in this scope; did you mean ‘AFMT_S16_NE’?
 8914 |     if ( mask & AFMT_S24_NE ) {
      |                 ^~~~~~~~~~~
      |                 AFMT_S16_NE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8918:22: error: ‘AFMT_S24_OE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8918 |     else if ( mask & AFMT_S24_OE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8925:17: error: ‘AFMT_S32_NE’ was not declared in this scope; did you mean ‘AFMT_S16_NE’?
 8925 |     if ( mask & AFMT_S32_NE ) {
      |                 ^~~~~~~~~~~
      |                 AFMT_S16_NE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8929:22: error: ‘AFMT_S32_OE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8929 |     else if ( mask & AFMT_S32_OE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8942:22: error: ‘AFMT_S32_NE’ was not declared in this scope; did you mean ‘AFMT_S16_NE’?
 8942 |     else if ( mask & AFMT_S32_NE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_NE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8946:22: error: ‘AFMT_S24_NE’ was not declared in this scope; did you mean ‘AFMT_S16_NE’?
 8946 |     else if ( mask & AFMT_S24_NE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_NE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8950:22: error: ‘AFMT_S16_OE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8950 |     else if ( mask & AFMT_S16_OE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8955:22: error: ‘AFMT_S32_OE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8955 |     else if ( mask & AFMT_S32_OE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:8960:22: error: ‘AFMT_S24_OE’ was not declared in this scope; did you mean ‘AFMT_S16_BE’?
 8960 |     else if ( mask & AFMT_S24_OE ) {
      |                      ^~~~~~~~~~~
      |                      AFMT_S16_BE
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9027:32: error: call of overloaded ‘abs(unsigned int)’ is ambiguous
 9027 |   if ( abs( srate - sampleRate ) > 100 ) {
      |                                ^
In file included from /usr/include/c++/9/cstdlib:75,
                 from /usr/include/c++/9/ext/string_conversions.h:41,
                 from /usr/include/c++/9/bits/basic_string.h:6493,
                 from /usr/include/c++/9/string:55,
                 from /srv/arch/mlt/src/modules/rtaudio/RtAudio.h:50,
                 from /srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:43:
/usr/include/stdlib.h:840:12: note: candidate: ‘int abs(int)’
  840 | extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
      |            ^~~
In file included from /usr/include/c++/9/cstdlib:77,
                 from /usr/include/c++/9/ext/string_conversions.h:41,
                 from /usr/include/c++/9/bits/basic_string.h:6493,
                 from /usr/include/c++/9/string:55,
                 from /srv/arch/mlt/src/modules/rtaudio/RtAudio.h:50,
                 from /srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:43:
/usr/include/c++/9/bits/std_abs.h:79:3: note: candidate: ‘constexpr long double std::abs(long double)’
   79 |   abs(long double __x)
      |   ^~~
/usr/include/c++/9/bits/std_abs.h:75:3: note: candidate: ‘constexpr float std::abs(float)’
   75 |   abs(float __x)
      |   ^~~
/usr/include/c++/9/bits/std_abs.h:71:3: note: candidate: ‘constexpr double std::abs(double)’
   71 |   abs(double __x)
      |   ^~~
/usr/include/c++/9/bits/std_abs.h:61:3: note: candidate: ‘long long int std::abs(long long int)’
   61 |   abs(long long __x) { return __builtin_llabs (__x); }
      |   ^~~
/usr/include/c++/9/bits/std_abs.h:56:3: note: candidate: ‘long int std::abs(long int)’
   56 |   abs(long __i) { return __builtin_labs(__i); }
      |   ^~~
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp: In member function ‘virtual void RtApiOss::closeStream()’:
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9206:29: error: ‘SNDCTL_DSP_HALT’ was not declared in this scope; did you mean ‘SNDCTL_COPR_HALT’?
 9206 |       ioctl( handle->id[0], SNDCTL_DSP_HALT, 0 );
      |                             ^~~~~~~~~~~~~~~
      |                             SNDCTL_COPR_HALT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9208:29: error: ‘SNDCTL_DSP_HALT’ was not declared in this scope; did you mean ‘SNDCTL_COPR_HALT’?
 9208 |       ioctl( handle->id[1], SNDCTL_DSP_HALT, 0 );
      |                             ^~~~~~~~~~~~~~~
      |                             SNDCTL_COPR_HALT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp: In member function ‘virtual void RtApiOss::stopStream()’:
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9304:36: error: ‘SNDCTL_DSP_HALT’ was not declared in this scope; did you mean ‘SNDCTL_COPR_HALT’?
 9304 |     result = ioctl( handle->id[0], SNDCTL_DSP_HALT, 0 );
      |                                    ^~~~~~~~~~~~~~~
      |                                    SNDCTL_COPR_HALT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9314:36: error: ‘SNDCTL_DSP_HALT’ was not declared in this scope; did you mean ‘SNDCTL_COPR_HALT’?
 9314 |     result = ioctl( handle->id[1], SNDCTL_DSP_HALT, 0 );
      |                                    ^~~~~~~~~~~~~~~
      |                                    SNDCTL_COPR_HALT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp: In member function ‘virtual void RtApiOss::abortStream()’:
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9350:36: error: ‘SNDCTL_DSP_HALT’ was not declared in this scope; did you mean ‘SNDCTL_COPR_HALT’?
 9350 |     result = ioctl( handle->id[0], SNDCTL_DSP_HALT, 0 );
      |                                    ^~~~~~~~~~~~~~~
      |                                    SNDCTL_COPR_HALT
/srv/arch/mlt/src/modules/rtaudio/RtAudio.cpp:9360:36: error: ‘SNDCTL_DSP_HALT’ was not declared in this scope; did you mean ‘SNDCTL_COPR_HALT’?
 9360 |     result = ioctl( handle->id[1], SNDCTL_DSP_HALT, 0 );
      |                                    ^~~~~~~~~~~~~~~
      |                                    SNDCTL_COPR_HALT
make[2]: *** [src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/build.make:76：src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/RtAudio.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:679：src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

**Comment by ddennedy** [comment] 2021-07-02 07:19
Duplicate of #716

**Closed by ddennedy** 2021-07-02 07:19 UTC
