### ISSUE TITLE
FFmpeg 4.3 compatibility

### ISSUE THREAD

**Issue by eszlari** [mltframework/mlt#612] opened 2020-10-22 17:02 UTC
In this [Shotcut commit](https://github.com/mltframework/shotcut/commit/42314e399bb66bc9542fb6b72dc44d2f30b5aafe) FFmpeg was reverted to 4.2. Should all MLT based editors do the same?

**Comment by ddennedy** [comment] 2020-10-23 06:56
Ok, this downgrade has fixed the situation for my affected Windows user, and I am going to leave it at 4.2 for the next version. I am not certain if it affects Linux users or the root cause. I suspect it may use a certain cpu feature that makes it fail dlopen? Very strange. I had this user also test the Microsoft store version of the app using FFmpeg 4.3 that runs in a confined manner with a unique default configuration, and that did not work either.

https://forum.shotcut.org/t/impossible-for-me-to-add-mp4-in-playlist-with-the-version-20-09-13/21227/15

**Comment by eszlari** [comment] 2020-10-23 12:07
Maybe related: https://github.com/olive-editor/olive/issues/1176

**Comment by sandsmark** [comment] 2020-12-15 17:22
That's a crash (and trivial to fix, just need to make sure buffers are properly aligned), but the issue on windows seems to be failure to load the plugin?

**Comment by ddennedy** [comment] 2020-12-15 23:07
> the issue on windows seems to be failure to load the plugin?

Correct, and no buffers are allocated and passed to simply load the MLT module, which is a very curious problem that only affects a small portion of users. There was a whole release cycle with hundreds of thousands of downloads, and no one reporting a crash like Olive experienced when trying to actually decode.

> I think just changing IMAGE_ALIGN to 16 everywhere should be sufficient

It is not exactly that simple. MLT's yuv420p image format does not support padding between planes in order to guarantee alignment. However, it has very limited support for yuv420p, and that can be addressed in MLT v7. Something similar is needed for non-interleaved audio as well, and that is a bigger task.

**Comment by sandsmark** [comment] 2020-12-16 14:00
> It is not exactly that simple. MLT's yuv420p image format does not support padding between planes in order to guarantee alignment

That makes it a bit trickier. But I saw that IMAGE_ALIGN wasn't the same everywhere, it was 4 bytes in one file iirc, so it might work to just bump it there in case things start crashing (assuming it uses that only when handing stuff to ffmpeg or something).

(I'm not 100% sure I understood why it needs padding between planes for the alignment, though, but improving yuv420p support everywhere sounds like a good thing anyways.)

**Comment by ddennedy** [comment] 2020-12-16 17:16
> I'm not 100% sure I understood why it needs padding between planes for the alignment

FFmpeg wants buffers to be 16-byte aligned, and planes and channels of data are distinct buffers in its API but not in MLT's.

> improving yuv420p support everywhere

I think you misunderstand. There is not a plan to add yuv420p to many things. The idea is to add APIs that understand the starting address of each plane for planar formats instead of assuming they contiguously follow one another in memory.

**Closed** 2021-12-19 19:47 UTC
Labels: expired
