### ISSUE TITLE
SDL2 support ? 

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#112] opened 2016-04-21 05:00 UTC
Linux Fedora have SDL1 and SDL2 , but SDL2 should be better 
as request in https://sourceforge.net/p/mlt/bugs/228/
Please add support for building with SDL2: it is now stable and included in many distros.

Thanks

**Comment by RJVB** [comment] 2017-04-30 09:58
I second that!

A year later we're at the point where more and more applications depending on MLT have their own dependency on SDL2; on Mac that means we get warnings like 

```
objc[53849]: Class SDLTranslatorResponder is implemented in both /opt/local/lib/libSDL-1.2.0.dylib and /opt/local/lib/libSDL2-2.0.0.dylib. One of the two will be used. Which one is undefined.
```

For now that seems to pose no problem but if MLT really requires SDL it should really provide an option to use either version.

**Comment by ddennedy** [comment] 2017-08-29 07:12
SDL2 support was added for the sdl and sdl_audio consumers but not yet sdl_still and sdl_preview. sdl_image producer is being deprecated. Once the above 2 are done I will close this.

**Comment by sergiomb2** [comment] 2017-11-02 00:26
I started to test it on Fedora rawhide , commit from 21 September 

https://koji.fedoraproject.org/koji/packageinfo?packageID=22570

**Comment by jliljebl** [comment] 2017-11-02 08:20
Current MLT master with SDL2 breaks Flowblade and I've been trying to get it to work but I'm not sure it can be done. I'll keep at it, but the only way I can see forward is to start patching SDL2 code, I've tried everything the API offers and it still hangs in libcairo when it calls libX11.

Maybe we could add a new module "sdl2" which uses SDL2 and revert the old "sdl" module to state before it was converted to using SDL2 and leave that using SDL1.2 and make compiling these modules optional.

I don't know what improvements SDL2 brings to MLT, but from video display point of view it's a regression and breaks existing applications. One option is to leave it at least for one more release.

**Comment by RJVB** [comment] 2017-11-02 09:38
If patching SDL2 code leads to upstreamable contributions that should be an improvement for everyone then please explore that path.

I brought up SDL2 support a while back because mixing SDL and SDL2 use in a single application could lead to problems at least on Mac. I tinkered with SDL *long* ago and didn't even know about SDL2 until I started seeing system warnings about a SDL/SDL2 class name conflict. Is it supposed to be possible to use both libraries in a single application, one way or another?

If not, then maybe MLT should explore a runtime mechanism to select which backend is to be used. Hard to say how useful that will really be given that an applicating using an MLT feature requiring SDL could still be using SDL2 directly for something else.

I guess what I'm trying to do here is figure out if we should report the class nameconflict issue back to the SDL team.

**Comment by sergiomb2** [comment] 2017-11-02 12:29
@jliljebl if it is in RPMFusion please open a quick report on 
https://bugzilla.rpmfusion.org/enter_bug.cgi?product=Fedora

it will be very useful

**Comment by jliljebl** [comment] 2017-11-02 12:52
This is what I found:

http://rpmfind.net/linux/RPM/rpmfusion/free/fedora/updates/24/i386/f/flowblade-1.12.0-1.gitfd577a9.fc24.noarch.html

When I did search here: https://koji.fedoraproject.org/koji/packages for flowblade, I did not find anything.

**Comment by jliljebl** [comment] 2017-11-02 13:04
Ok, I filed this: https://bugzilla.rpmfusion.org/show_bug.cgi?id=4696.

**Comment by ddennedy** [comment] 2018-01-21 20:53
New release is coming tomorrow that includes sdl2 module that can be built alongside or instead of sdl (1.2) module.

**Closed by ddennedy** 2018-01-21 20:53 UTC
Labels: resolved

**Comment by sergiomb2** [comment] 2018-01-21 21:59
Hi, 
I thanks for the info , I have a quick question for you if you may have 5 minutes ,  did MTL needs / uses libquicktime for anything ?

**Comment by ddennedy** [comment] 2018-01-21 23:31
> MLT needs / uses libquicktime for anything ?
no
