### ISSUE TITLE
First two frames of MP4/H.264 clips with b-frames ignored by MLT 

### ISSUE THREAD

**Issue by lvml** [mltframework/mlt#89] opened 2015-10-25 00:29 UTC
For a long time I have been struggling with MLT (as used in kdenlive, which I use) ignoring the first two frames of clips that my camera recorded. Since not only MLT, but also other software using ffmpeg exhibited similar behaviour, I was unable to really track down the cause of this - until very recently.

I had opened an issue with mpv, which was also not displaying the first frames of such files, and that was recently fixed with a work-around, see https://github.com/mpv-player/mpv/issues/1341 for reference.

There is also a ticket and some sort-of-fix to ffmpeg (as of May 2015) for what looks like the same problem here: https://trac.ffmpeg.org/ticket/4554

Based on these findings, I tried to figure out how to fix MLT such that kdenlive would also use the first frames of such MP4 / H.264 files with b-frames.

To reproduce the issue, please consider this file: http://filebin.ca/1knlOxMESIbK/P1000457.MP4 (3.5 MB < 3 seconds of 1280x720p25 video as recorded by a Panasonic camera, no software conversion in between).
It shows a screen with a millisecond counter, so it's easy to tell exactly what frame is on display. 
When replayed in the camera or with the latest (fixed) mpv version, the first frame shown shows time: 3685ms on the display. But MLT using software (like kdenlive) displays the frame showing "3768ms" as the first frame. And even worse, the last frames of the clip will be duplicates - causing ugly transitions to any subsequent clip.

I found that mlt/src/modules/avformat/producer_avformat.c, function find_first_pts(), would return the PTS of the third frame for such files. The DTS of the packet the function looks at is negative. I'm not sure I fully understood the whole chain of events leading up to the wrong "first_pts" value, but I was able to implement some work-around that works for me:

```
--- src/modules/avformat/producer_avformat.c.orig       2015-10-25 01:24:49.320922931 +0200
+++ src/modules/avformat/producer_avformat.c    2015-10-25 02:01:59.453888378 +0200
@@ -781,6 +781,18 @@
 {
        self->invalid_pts_counter += pts == AV_NOPTS_VALUE;
        self->invalid_dts_counter += dts == AV_NOPTS_VALUE;
+
+       if ((dts != AV_NOPTS_VALUE) && (dts < 0)) {
+               // Decoding Time Stamps with negative values are reported by ffmpeg code for 
+               // (at least) MP4 files containing h.264 video using b-frames.
+               // For reasons not understood yet, the first PTS computed then is that of the
+               // third frame, causing MLT to display the third frame as if it was the first.
+               // This if-clause is meant to catch and work around this issue - if there is
+               // a valid, but negative DTS value, we just guess that the first valid
+               // Presentation Time Stamp is == 0.
+               return 0;
+       }
+
        if ( ( self->invalid_pts_counter <= self->invalid_dts_counter
                   || dts == AV_NOPTS_VALUE ) && pts != AV_NOPTS_VALUE )
                return pts;
```

I'm kind of sure there are better / cleaner methods than the crude fix above to fix the issue, maybe you can implement one?

**Comment by ddennedy** [comment] 2015-11-03 05:30
I started looking into this, and I see what you mean. However, a change to best_pts() is not a good choice, better to modify find_first_pts() like this:
```
--- src/modules/avformat/producer_avformat.c
+++ src/modules/avformat/producer_avformat.c
@@ -837,7 +837,10 @@ static void find_first_pts( producer_avformat self, int video_index )
 			mlt_log_debug( MLT_PRODUCER_SERVICE(self->parent),
 				"first_pts %"PRId64" dts %"PRId64" pts_dts_delta %d\n",
 				pkt.pts, pkt.dts, (int)(pkt.pts - pkt.dts) );
-			self->first_pts = best_pts( self, pkt.pts, pkt.dts );
+			if ( pkt.dts != AV_NOPTS_VALUE && pkt.dts < 0 )
+				self->first_pts = 0;
+			else
+				self->first_pts = best_pts( self, pkt.pts, pkt.dts );
 			if ( self->first_pts != AV_NOPTS_VALUE )
 				toscan = 0;
 		}
```
I need to check for a possible regression. I am trying to find other samples in my collection that have a similar initial DTS/PTS problem, and I see some GoPro samples do and not much else. However, I want to see how if the change could possibly affect A/V sync, but so far none of my samples including yours can help with that. Can you make another sample where you are tapping on something with your finger or pen?

**Comment by lvml** [comment] 2015-11-03 20:43
Sure, here you go: http://filebin.net/jht6hcyv08/P1020463.MP4  (3.4 MB).

This tiny sample, also directly from the camera, shows a chronometer running alongside me tapping some cutlery on a lens cap.

In the bigger, lower row of the watch the first frame should show the numbers "38.37", with the ".37" just materializing, in the second frame the .37 is complete, the third frame shows a .40 half materialized (which is the frame mistaken to be the first without the patch).

**Comment by ddennedy** [comment] 2015-11-04 04:28
I applied the MLT audiowaveform filter to P1020463.MP4 and rendered as image sequence. Here is frame 30 (1-based) from before the change:
![p1020463-30](https://cloud.githubusercontent.com/assets/1146683/10929439/370cc4c6-8268-11e5-88da-535002f09873.png)

Notice that the audio tap is occurring slightly before contact is made. Here is frame 32 from after the code change:
![p1020463-32](https://cloud.githubusercontent.com/assets/1146683/10929459/b4c58420-8268-11e5-9315-8dfa6427cb7f.png)

Audio waveform activity has not yet started - good. Frame 33 from after the change is perhaps the initial point of contact, but not much audio activity:
![p1020463-33](https://cloud.githubusercontent.com/assets/1146683/10929479/fe230eee-8268-11e5-80f9-2ccf36e2acfe.png)

And here is frame 34 from after the change. By this time contact is definitely being made and perhaps some delay is due to speed of sound vs. light.
![p1020463-34](https://cloud.githubusercontent.com/assets/1146683/10929470/d5112bbc-8268-11e5-9a26-3136a8e4a8bc.png)

I believe A/V sync is improved by this change.

**Comment by lvml** [comment] 2015-11-05 22:47
Great!

Just one more question: I'm not sure whether this is just a strange misbehaviour or numeric imprecision somewhere in kdenlive, but when I pull the clip to the timeline of an (also 25fps) project in kdenlive, even with the patch, the last frame of the video is sometimes a duplicate of the second to last frame, and sometimes is it not. Can you say, from the perspective of MLT, whether the length of the clip - as reported by MLT - is an exact match to the number of frames that are decoded from it?

**Comment by ddennedy** [comment] 2015-11-05 23:37
It is determined by a heuristic based on libavformat. It is too expensive to try to decode the entire file just to determine duration! Here is the line that calculates duration:
https://github.com/mltframework/mlt/blob/master/src/modules/avformat/producer_avformat.c#L572
It will require a some strongly convincing reason to change it, I think. mlt_profile_fps() is the project fps in Kdenlive's terms.

**Comment by bmatherly** [comment] 2015-11-06 19:16
I have observed the same problem in both KDENLIVE and Shotcut. It is a little annoying to go through each clip on the timeline just to cut off the last few frames. But I haven't found a suitable solution yet. If anyone comes up with a good solution, I would be glad to listen. 

I considered changing the lrint() to  round down instead of rounding to nearest. But I find that there is often more than one frame repeated at the end - so rounding down by one frame won't fix all cases. It might still be worth considering rounding down since any rounding up would always result in a single repeated frame minimally.

The only thing I can think of would be to have the application automatically set the length 5 frames shorter than the duration reported by MLT. But that isn't an extensible solution for all use cases.

**Comment by wrosecrans** [comment] 2015-11-06 19:36
On Fri, Nov 6, 2015 at 11:16 AM, Brian Matherly <notifications@github.com>
wrote:

> I have observed the same problem in both KDENLIVE and Shotcut. It is a
> little annoying to go through each clip on the timeline just to cut off the
> last few frames. But I haven't found a suitable solution yet. If anyone
> comes up with a good solution, I would be glad to listen.
>

When I was working on an internal editing application a while back, I used
a library called ffms2 that fully indexed a video file that the user
dropped onto the timeline and cached the index so that users would only
incur the hit of decoding/indexing the full file the first time they
imported it into the app.  I never did find a 100% solid way to do reliable
arbitrary seeking and frame accurate lengths across all the files I tested
with.

What you can do it use something like the current way MLT does it as an
initial estimate and update the UI, then do full decode+index of any format
that needs it as a background task and update the initial estimate when you
have more accurate metadata.

**Comment by ddennedy** [comment] 2015-11-06 22:10
There have been changes to the duration calc in the past, and sometimes people complain there are too many frames and other times there are too few frames. So, I plan to keep it where it is. @wrosecrans idea is not bad, and you can override the MLT calculated duration by setting the length and out properties.
P.S. I will close this ticket on the next release.

**Closed** 2016-02-18 00:04 UTC
Labels: resolved
