### ISSUE TITLE
melt 6.5.0 hangs on certain .mp4 video file

### ISSUE THREAD

**Issue by TheDiveO** [mltframework/mlt#166] opened 2017-01-05 15:08 UTC
My HDMI recorder generated an MP4 video file (~6MB) which plays and seeks totally fine in ffplay 3.0.5, but hangs melt 6.5.0, when seeking around a certain frame region (approx. frame 383 or so). A normal play from start to end won't hang melt, but seeking in the video around the problematic region causes melt to stop responding and causing some moderate, permanent CPU load; probably a single core. I've only found this issue because Kdenlive hangs while seeking this specific MP4 video in its clip monitor.

My OS is Kubuntu 16.10; ffplay is 3.0.5-0ubuntu0.16.10.1 from the Ubuntu repos; melt is 6.5.0 from the Kdenlive master ppa, which is compiled from this repository, as far as I know.

**Comment by walterav1984** [comment] 2017-02-05 21:14
This is also the case for me with melt 6.5.x with patch #182 and h264 1080i_50 broadcast transport streams on decklink consumer atsc_1080i_50, it will only play less than the first ~95 frames than it stops. Playback with melt 6.0.0 from the ubuntu 16.04 repo is not affected and plays correctly.

FFProbe output:
`Input #0, mpegts, from '/home/ubuntuadmin/Downloads/NPO-2-HD.ts':
  Duration: 00:38:49.06, start: 82567.858511, bitrate: 13359 kb/s
  Program 19402 
    Metadata:
      service_name    : NPO 2 HD
      service_provider: ZiggoL
    Stream #0:0[0x8fd]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x907](dut): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s
    Stream #0:2[0x908](dut): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 448 kb/s
    Stream #0:3[0x909](GOS): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s (visual impaired)
    Stream #0:4[0x961](dut): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250
    Stream #0:5[0x962](dut): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
    Stream #0:6[0x963](dut): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)`

Although complaining about PES mismatch and subtitle streams it plays well with melt 6.0.0:
`[NULL @ 0xba4c80] start time for stream 5 is not set in estimate_timings_from_pts
[NULL @ 0xbbfc20] start time for stream 6 is not set in estimate_timings_from_pts
[mpegts @ 0xb9cf00] PES packet size mismatch
[mpegts @ 0xb9cf00] PES packet size mismatch
[mpegts @ 0xb9cf00] PES packet size mismatch
[mpegts @ 0xb9cf00] PES packet size mismatch
[NULL @ 0xd23680] start time for stream 5 is not set in estimate_timings_from_pts
[NULL @ 0xd24220] start time for stream 6 is not set in estimate_timings_from_pts
[mpegts @ 0xc3a7e0] PES packet size mismatch
[mpegts @ 0xc3a7e0] PES packet size mismatch
[mpegts @ 0xc3a7e0] PES packet size mismatch
[mpegts @ 0xc3a7e0] PES packet size mismatch
[NULL @ 0xc30500] start time for stream 5 is not set in estimate_timings_from_pts
[NULL @ 0xc310a0] start time for stream 6 is not set in estimate_timings_from_pts
[mpegts @ 0xd27740] PES packet size mismatch
[mpegts @ 0xd27740] PES packet size mismatch
[mpegts @ 0xd27740] PES packet size mismatch
[mpegts @ 0xd27740] PES packet size mismatch
[h264 @ 0x7f94100da320] reference picture missing during reorder
[h264 @ 0x7f94100da320] Missing reference picture, default is 65516
[h264 @ 0x7f94100ce560] reference picture missing during reorder
[h264 @ 0x7f94100ce560] Missing reference picture, default is 65517
[h264 @ 0x7f9411384e80] reference picture missing during reorder
[h264 @ 0x7f9411384e80] Missing reference picture, default is 65524
`

**Comment by ddennedy** [comment] 2017-02-05 22:00
This might be fixed in recent commit d25ba846d68f2d80a0d3d5a3bd48639784c8f48c or at least related.

In my case, I found a problem when trying to play a network stream where it would hang on the first frame. In this case, maybe the condition `self->seekable` should be removed because the test condition before regression in 0dbd50abe9f23cef5ea51f92b7506fdd08cf33f0  was simply `if ( int_position > 0 )`. It would be great if either of you can see if removing `self->seekable ||` from the current version resolves it.

**Comment by walterav1984** [comment] 2017-02-06 07:54
I removed `self->seekable || ` from line 2451 of #182 version so it states `		if ( int_position > 0 )`. 
Than compiled and tested but its still freezing(still responds to q for quiting) after less than ~100 frames. Mind I just play files, don't seek them mentioned by the issue starter.
`make clean;make;source setenv;src/melt/melt -profile atsc_1080i_50 hd1080i50testh264footage.ts -consumer decklink`

**Comment by walterav1984** [comment] 2017-02-06 08:05
I also patched #182 to the state of 0dbd50a and it still freezes after less than ~80 frames. Strange thing is that press 'q' tot quit melt still gives some extra debug info in @max-verem his version.

sliced_420_pix_fmt_conv_proc:1282: [id=56, idx=28, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1792 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=57, idx=28, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1792 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=58, idx=29, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1856 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=59, idx=29, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1856 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
Current Position:         80 #pressing 'q' moment
sliced_420_pix_fmt_conv_proc:1282: [id=0, idx=0, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=0 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=1, idx=0, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=0 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=2, idx=1, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=64 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=3, idx=1, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=64 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=4, idx=2, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=128 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=5, idx=2, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=128 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=6, idx=3, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=192 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=7, idx=3, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=192 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=8, idx=4, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=256 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=9, idx=4, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=256 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=10, idx=5, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=320 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=11, idx=5, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=320 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=12, idx=6, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=384 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=13, idx=6, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=384 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=14, idx=7, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=448 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=15, idx=7, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=448 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=16, idx=8, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=512 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=17, idx=8, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=512 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=18, idx=9, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=576 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=19, idx=9, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=576 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=20, idx=10, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=640 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=21, idx=10, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=640 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=22, idx=11, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=704 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=23, idx=11, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=704 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=24, idx=12, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=768 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=25, idx=12, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=768 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=26, idx=13, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=832 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=27, idx=13, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=832 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=28, idx=14, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=896 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=29, idx=14, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=896 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=30, idx=15, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=960 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=31, idx=15, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=960 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=32, idx=16, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1024 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=33, idx=16, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1024 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=34, idx=17, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1088 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=35, idx=17, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1088 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=36, idx=18, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1152 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=37, idx=18, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1152 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=38, idx=19, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1216 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=39, idx=19, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1216 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=40, idx=20, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1280 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=41, idx=20, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1280 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=42, idx=21, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1344 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=43, idx=21, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1344 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=44, idx=22, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1408 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=45, idx=22, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1408 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=46, idx=23, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1472 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=47, idx=23, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1472 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=48, idx=24, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1536 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=49, idx=24, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1536 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=50, idx=25, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1600 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=51, idx=25, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1600 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=52, idx=26, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1664 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=53, idx=26, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1664 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=54, idx=27, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1728 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=55, idx=27, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1728 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=56, idx=28, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1792 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=57, idx=28, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1792 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=58, idx=29, jobs=60], interlaced=1, field=0, slices=30, mul=2, h=540, slice_w=64, slice_x=1856 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]
sliced_420_pix_fmt_conv_proc:1282: [id=59, idx=29, jobs=60], interlaced=1, field=1, slices=30, mul=2, h=540, slice_w=64, slice_x=1856 ctx->desc=[log2_chroma_h=1, log2_chroma_w=1]``

**Comment by walterav1984** [comment] 2017-02-06 08:33
Trying native github commit versions (each version before the version you stated and latest) all plays fine for me: 81f77b8, 0dbd50a, f8c228e, d25ba84, bf2749a. So I guess my freeze playing bug is somewhere between these versions and @max-verem patch #182?

**Comment by walterav1984** [comment] 2017-02-06 08:51
Also tried @max-verem 19cfc58 avformat_1fixes, f70d47c minor_fixes_20170205 these also play fine without freeze.

Retried @max-verem #182 fb09410 and thats the one that freezes playback, maybe it is something CPU threading bound because of HD h264 footage requires more of PC? I have old Intel Cpu Core2quad motherboard modded to Xeon E5472, it has 4 cores and 6GB ddr2 ram.

**Comment by max-verem** [comment] 2017-02-06 12:54
could you provide a samples to reproduce this behavior?

**Comment by walterav1984** [comment] 2017-02-06 19:35
Freezing won't happen if consumer is SDL instead of Decklink. 

I'm sending a example video link to your mail at m1.tv, will be there in 20 minutes.

**Comment by walterav1984** [comment] 2017-02-06 19:36
PS: sorry @TheDiveO for hijacking this issue.

**Comment by max-verem** [comment] 2017-02-07 14:51
reason of *hanging* related to decklink consumer arch and caused by very high cpu load because of very precise chroma calculating. running command:
```
melt -debug -profile dv_pal demo.ts -consumer decklink:3 preroll=12 realtime=-4
```
plays without hanging

**Comment by ddennedy** [comment] 2017-02-08 16:48
What happens if you use "real_time=-4" instead of "reatime=-4" ?

**Comment by walterav1984** [comment] 2017-02-08 19:00
When using "real_time=-4" compared to "realtime=x" it keeps playing albeit very slow, although melt CPU usage on Xeon E5472 keeps around 120% from 400% total.

`src/melt/melt -profile dv_pal_wide ~/Desktop/klokhuis-NPO-3-HD.ts -consumer decklink preroll=12 real_time=-4`

Increasing the preroll seems to increase smooth playback for the first seconds of the clip before it shows down like preroll=50 gives 2 seconds of fluent motion.

**Comment by TheDiveO** [comment] 2017-02-09 20:54
I'm not dead yet ... the video part is H.264 1080p 30fps, recorded by a Hauppauge Rocket HD PVR stand-alone HDMI recorder. As I said, I can supply the file, but not to the public.

**Comment by TheDiveO** [comment] 2017-02-10 15:50
Bad news: I've tested using the Kdenlive ppa build of MLT dated from 2017/02/04, so it's clearly after the commit d25ba84, and **MLT still hangs** while scrubbing my video.

ffprobe says:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'foobar.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: qt  
  Duration: 00:01:04.90, start: 0.000000, bitrate: 996 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 174 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 814 kb/s, 29.03 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```

**Comment by ddennedy** [comment] 2017-02-10 18:33
You can upload a file using https://shotcut.org/notes/support-upload/ which uses MediaFire to discreetly share a file. It is not entirely private, but as long as the link to the file is not shared, it is not indexed, and I delete the file after I download it (not 100% sure it gets deleted, but it does invalidate HTTP access to it).
An alternative is for you to use a cloud drive service and share with me by my e-mail address ddennedy at gmail dot com.

**Comment by TheDiveO** [comment] 2017-02-11 13:44
Dan, thank you very much for your kind offer to take a look at the video file. I've shared it with you through Google Drive. Best regards, Harald

**Comment by ddennedy** [comment] 2017-02-11 22:00
I got the sample file provided by @TheDiveO and reproduced the problem and started looking into it. It is a problem in every version of Shotcut I tried between 17.02 and 14.09! I think I have a fix.

**Closed** 2017-02-12 02:09 UTC

**Comment by TheDiveO** [comment] 2017-02-12 07:26
Good to see you could reproduce the hang and come up with a fix! Thank you very much for the time you put into this.

**Comment by TheDiveO** [comment] 2017-02-12 14:08
I could now test the fix and it works great for me, thank you very much.
