### ISSUE TITLE
Movit integration with MLT

### ISSUE THREAD

**Issue by Augadh1** [mltframework/mlt#886] opened 2023-03-16 03:32 UTC
Hi,
I setup mlt on aws EC2 instance. OS installed is ubuntu 22.04.
I am trying to run melt command having one video and applying movit.glow effect.
Here is the screenshot of the output.
![movit-issue](https://user-images.githubusercontent.com/39818153/225504580-99c62852-4738-470b-b140-94f5a81abf30.jpg)
![audio](https://user-images.githubusercontent.com/39818153/225506043-246d67f2-63bd-4d75-a9f4-e5f29207d2e7.jpg)

As there is no audio device I am suspecting due to this command i am running is stuck.
EC2 does not provide any service to add audio card on ec2 instance.
So, I am thinking of creating a virtual audio card will resolve this issue.
Link to create dummy audio card.
https://superuser.com/questions/344760/how-to-create-a-dummy-sound-card-device-in-linux-server

@ddennedy , can you suggest is it a best way or any other way which can work ?

**Comment by ddennedy** [comment] 2023-03-16 06:06
Your avformat module is not working. So, it is falling back to the default consumer sdl2, which is why there is a "[consumer sdl2]..." line in your output. Otherwise, you do not need an audio device.
You might find it convenient to use our docker image available through the docker hub as `mltframework/melt`. 
Also, you should be aware that movit filters require OpenGL, which is not easy to get working in an headless environment like EC2. I do not have experience with that with MLT.
Closing this as it is not a bug.

**Closed by ddennedy** 2023-03-16 06:06 UTC
