### ISSUE TITLE
Filter volume stopped to work..

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#400] opened 2019-01-13 10:20 UTC
```
	melt 
	"11 mute.mp4" -mix 7 -mixer luma  
	"21.mp4" -mix 7 -mixer luma  
	"22.mp4" -mix 7 -mixer luma  
	...
	"Finish.mov" -mix 7 -mixer luma
	-audio-track "tmp.mp3" out=3729 -transition mix in=0 out=3729 a_track=0 b_track=1 
	-filter volume level="0=-14;366=-14;381=0;3699=0;3729=-100;"
	-profile atsc_1080p_2997
	-consumer avformat:"out.mp4" vcodec=libx264 vb=4500k ab=128k strict=-2
```
Filter volume did not change volume of soundtrack on latest mlt (worked fine on 0.9.6)
Any suggestion with that?

**Comment by ddennedy** [comment] 2019-01-13 20:53
What do you mean by "latest"? Yesterday, in git master there was a regression in commit aaebba4 that caused the mix transition to fail, but the volume filter still works in your command line. This was just fixed in 2dece18, and now I do not reproduce your problem.

**Comment by DangerD256** [comment] 2019-01-14 06:14
Downloaded again latest from git:
```
melt -version
melt 6.13.0
```
I'll try 0.96 now

**Comment by ddennedy** [comment] 2019-01-14 06:17
What? Provide the git sha1sum of "latest"

**Comment by DangerD256** [comment] 2019-01-14 06:33
28837fe85cb3e93bb32d35b57f4cd308ae1b7e85  master.zip
0.9.6 is not available, so i can't check it...

Produced video:
https://www.youtube.com/watch?v=pTyAdETIxYA

Whole run command:
```
melt 
"11 mute.mp4" -mix 7 -mixer luma  
"21.mp4" -mix 7 -mixer luma  
"22.mp4" -mix 7 -mixer luma  
"23.mp4" -mix 7 -mixer luma  
"24.mp4" -mix 7 -mixer luma  
"25.mp4" -mix 7 -mixer luma  
"26.mp4" -mix 7 -mixer luma  
"27.mp4" -mix 7 -mixer luma  
"28.mp4" -mix 7 -mixer luma  
"29.mp4" -mix 7 -mixer luma  
"30.mp4" -mix 7 -mixer luma  
"31.mp4" -mix 7 -mixer luma  
"32.mp4" -mix 7 -mixer luma  
"33.mp4" -mix 7 -mixer luma  
"34.mp4" -mix 7 -mixer luma  
"1547447289.mp4" -mix 7 -mixer luma  
"42.mp4" -mix 7 -mixer luma  
"43.mp4" -mix 7 -mixer luma  
"44.mp4" -mix 7 -mixer luma  
"45.mp4" -mix 7 -mixer luma  
"46.mp4" -mix 7 -mixer luma  
"47.mp4" -mix 7 -mixer luma  
"48.mp4" -mix 7 -mixer luma  
"49.mp4" -mix 7 -mixer luma 
-filter watermark:"caption2.png" in=352.1475 out=501.9975 composite.progressive=1 producer.align=centre composite.valign=b composite.halign=c composite.geometry="0=0,90:100%x100%:100%;14.985=0,0:100%x100%:100%;142.3575=0,0:100%x100%:100%;149.85=0,90:100%x100%:0%"  -filter watermark:"/home/mediat/tmp/#314-90 Orchid Place Drive Scarborough, Jyoti Sharma/15474472991503900598.jpg" in=367.1325 out=495 composite.progressive=1 producer.align=centre composite.valign=b composite.halign=c composite.geometry="0=0,0:100%x100%:0%;7.4925=0,0:100%x100%:100%;104.5075=0,0:100%x100%:100%;112=0,0:100%x100%:0%" 
"Finish.mov" -mix 7 -mixer luma 
-audio-track "tmp.mp3" out=3729 -transition mix in=0 out=3729 a_track=0 b_track=1 
-filter volume level="0=-14;366=-14;381=0;3699=0;3729=-100;"  
-profile atsc_1080p_2997 
-consumer avformat:"out.mp4" vcodec=libx264 vb=4500k ab=128k strict=-2
```
Maybe i did something wrong...

**Comment by DangerD256** [comment] 2019-01-14 06:35
Music volume must be lowered during speech (1st video)

**Comment by ddennedy** [comment] 2019-01-15 01:00
The following works for me such that the audio of demo/music1.ogg starts lowered, raises, and then fades to silence:

> melt -profile dv_pal demo/clip1.dv -audio-track demo/music1.ogg out=299 -transition mix in=0 out=229 a_track=1 b_track=1 -filter volume level="0=-14;166=-14;81=0;99=0;229=-100;" -profile atsc_1080p_2997

I am not going to try to recreate your entire command line at this time. You need to try to simplify it to find a simpler example shows a problem.

In the future, when I say "git sha1sum" I mean a git commit ID of the latest change that `git log` reports and not the sha1sum of a zip file that you downloaded. This is how we track versions in git outside of releases.

**Comment by ddennedy** [comment] 2019-01-15 01:02
Version 0.9.6 is available on SourceForge: https://sourceforge.net/projects/mlt/files/mlt/

**Comment by DangerD256** [comment] 2019-02-04 09:54
```
melt   
"20 MUTE.mp4" 
-audio-track "tmp.mp3" out=350 -transition mix in=0 out=350 a_track=0 b_track=1 
-filter volume level="0=-14;100=-14;150=0;300=0;350=-14" 
-profile atsc_1080p_30  
-consumer avformat:"out.mp4" 
vcodec=libx264 vb=4500k ab=128k strict=-2
```
Can you please quickly check what i did wrong here?

**Comment by ddennedy** [comment] 2019-02-04 10:50
There is nothing wrong with that command. It does what you describe: the volume of tmp.mp3 starts lowered, raises to full volume, and then lowers again. If you cannot get it to work, then you have a bad build with a bug that is already fixed, and you are failing to properly upgrade.

**Closed by ddennedy** 2019-02-04 10:50 UTC

**Comment by DangerD256** [comment] 2019-02-04 11:54
Tried 0.9.6 and latest from git, doesn't works on both.
Previously worked fine on old server with 0.9.6 (installed from repo) and after updating to centos7 and installed latest from git volume filter stopped to work, also I had to add strict=-2"" to make aac encoder work, previosly worked well without it...

**Comment by DangerD256** [comment] 2019-02-04 11:55
Any suggestions?

**Comment by DangerD256** [comment] 2019-02-04 14:19
Maybe some other libraries causes this issue?

**Comment by DangerD256** [comment] 2019-02-05 09:01
`melt "tmp.mp3" out=350 -filter volume level="0=-14;100=-14;150=0;300=0;350=-14"`
This also doesn't works...

**Comment by DangerD256** [comment] 2019-02-05 09:12
Same problem is on another server (Centos7)
GIT:

> commit efe43e2ab119e286935a14440b5911caf0b67118
> Author: Dan Dennedy <dan@dennedy.org>
> Date:   Sat Feb 2 14:35:40 2019 -0800

...
installing by this commands:
```
make uninstall
./configure
make install
```

**Comment by DangerD256** [comment] 2019-02-05 14:03
Thanks a lot =)
