### ISSUE TITLE
Changed behavior in playback of mono audio tracks

### ISSUE THREAD

**Issue by ochilan** [mltframework/mlt#320] opened 2018-03-30 14:09 UTC
Hello,

I'm not sure if this is a bug or a feature. In any case, the behavior of playback of audio files has changed due to commit 7455472f47bc6a1ae38bf6260d1522070e08998f. I have not used mlt directly to reproduce this behavior but I'm seeing it in shotcut when using mlt in a version which includes said commit.

Previously, a mono audio track (for instance a voiceover track) was played back in stereo. The new behavior is that the mono track is output only on the left channel.

As a workaround, I can use the "Copy Channel" audio filter to copy the channel to the second channel. In principle this is also valid behavior – the question is if this behavior is intentional.

Best regards
Ochi

**Comment by bmatherly** [comment] 2018-03-30 14:37
The intended behavior is that a mono track will be duplicated to two stereo channels automatically. That is exactly what it does when I test Shotcut 18.03.06 on my Windows 10 PC with a mono clip.

What are the properties of the clip you are using (audio coding, etc)?

**Comment by ochilan** [comment] 2018-03-30 15:13
18.03.06 works correctly on my Linux box as well. Note that the mentioned commit is newer than the release version. I'm using the git versions of shotcut und mlt.

Just in case, I'm using PCM signed 16-bit little-endian 1-channel 48000 Hz WAVs.

**Comment by bmatherly** [comment] 2018-03-31 20:06
Thanks for the report. Fixed in 09d5ee2
Let me know if you see any other regressions.

**Closed by bmatherly** 2018-03-31 20:06 UTC
