### ISSUE TITLE
Segmentation fault when using qimage png producer

### ISSUE THREAD

**Issue by myuller** [mltframework/mlt#296] opened 2018-01-30 10:28 UTC
Hello, I have a sample xml file and a png that produce segfault in melt 6.6.0:

https://github.com/myuller/mlt-test

The line that segfaults is qimage_wrapper.cpp:265 https://github.com/mltframework/mlt/blob/aea7f984b85ac61a4052d6ae17ce981d0530548e/src/modules/qt/qimage_wrapper.cpp#L265 where the "src" variable seems to point into incorrect memory location.

Can anyone else reproduce this?

**Comment by bmatherly** [comment] 2018-01-31 03:16
I can confirm this issue using your files. I took a quick look, but nothing obvious popped out at me. For me, it was crashing after line 265 in the inner while loop.

**Comment by bmatherly** [comment] 2018-02-01 03:08
Fixed by #299

**Comment by ddennedy** [comment] 2018-02-01 04:32
Adding a note that this was due to the PNG using an 8-bit palette instead of more typical RGB format, which was unhandled.

**Closed by ddennedy** 2018-02-01 04:32 UTC
Labels: confirmed
