### ISSUE TITLE
Issue rendering simple scenarios on machine with more than 30+ cores

### ISSUE THREAD

**Issue by ydesgagn** [mltframework/mlt#725] opened 2021-07-21 00:36 UTC
We ran into issues with very simple scenarios on machine with 36, 64, 72 and 96 cores. We don't know why exactly and the core dump we captured pointed at this line but it doesn't make a lot of sense.

`in transport_action (producer=0x0, value=0x0) at /var/www/melt/src/mlt/src/melt/melt.c:212`

The workaround we found is to limit the number of slices in `build-melt.sh` by adding the middle line to patch the wrapper script to limit the slices count. At 29 or lower it's always working. At 30+ we get a segmentation fault each time.

```
export QML2_IMPORT_PATH="\$INSTALL_DIR/lib/qml"
export MLT_SLICES_COUNT=\$(grep -c "processor" /proc/cpuinfo | awk '{s=\$1; if (s>29) s=29; print s; }')
"\$INSTALL_DIR/bin/melt" "\$@"
```

Here are the versions we use:

```
# These are all of the configuration variables with defaults
AUTO_APPEND_DATE=0
SOURCE_DIR="$INSTALL_DIR/src"
ACTION_GET_COMPILE_INSTALL=1
ACTION_GET_ONLY=0
ACTION_COMPILE_INSTALL=0
SOURCES_CLEAN=1
INSTALL_AS_ROOT=0
CREATE_STARTUP_SCRIPT=1
BUNDLE_EXTRAS=1
ENABLE_FREI0R=1
FREI0R_HEAD=1
FREI0R_REVISION=v1.7.0
ENABLE_SWFDEC=0
SWFDEC_HEAD=
SWFDEC_REVISION=
ENABLE_MOVIT=1
MOVIT_HEAD=0
MOVIT_REVISION=1.6.3
LIBEPOXY_REVISION=1.5.4
X264_HEAD=0
X264_REVISION=5db6aa6cab1b146e07b60cc1736a01f21da01154
X265_HEAD=0
X265_REVISION=3.4
LIBVPX_HEAD=0
LIBVPX_REVISION=v1.10.0
ENABLE_LAME=1
FFMPEG_PROJECT="FFmpeg"
FFMPEG_HEAD=0
FFMPEG_REVISION=n4.4
FFMPEG_SUPPORT_H264=1
FFMPEG_SUPPORT_H265=1
FFMPEG_SUPPORT_LIBVPX=1
FFMPEG_SUPPORT_THEORA=1
FFMPEG_SUPPORT_MP3=1
FFMPEG_SUPPORT_FAAC=1
FFMPEG_SUPPORT_SSL=0
FFMPEG_ADDITIONAL_OPTIONS=
ENABLE_VIDSTAB=1
VIDSTAB_HEAD=0
VIDSTAB_REVISION=v1.1.0
MLT_HEAD=0
MLT_REVISION=v6.26.1
ENABLE_WEBVFX=0
WEBVFX_HEAD=0
WEBVFX_REVISION=1.2.0
ENABLE_RUBBERBAND=1
RUBBERBAND_HEAD=0
RUBBERBAND_REVISION=v1.9.2
MLT_DISABLE_SOX=0
MLT_DISABLE_SDL=0
MLT_SWIG_LANGUAGES="python"
```

We saw that starting with v6.24 and up.

Let us know if you need more information.

**Comment by ddennedy** [comment] 2021-07-21 19:31
We should probably limit slices in general because too many can make it less efficient as well due to CPU cache spoiling. I am not sure I can debug this, but I will try by forcing it to use more than my cpu count. I can definitely set the limit to 16, which is the way I am leaning. I have regularly used Shotcut on a machine with 16 logical processors for 5 years without this problem.

**Comment by ydesgagn** [comment] 2021-07-21 19:42
We identified the faulty effect on the time line to be:

`<property name="mlt_service">brightness</property>`

Without this it's running fine on 36 and 96 cores without limits.

**Comment by bmatherly** [comment] 2021-07-23 04:05
> We identified the faulty effect on the time line to be: brightness

That is a good clue. The brightness filter will divide the image up into as many slices as there are threads. Maybe dividing into too many slices causes math problems or overflows.

Can you test this simple patch and see if it avoids the crash for you?

```
diff --git a/src/modules/core/filter_brightness.c b/src/modules/core/filter_brightness.c
index 413a17e8..c6b90d3b 100644
--- a/src/modules/core/filter_brightness.c
+++ b/src/modules/core/filter_brightness.c
@@ -155,6 +155,7 @@ static int filter_get_image( mlt_frame frame, uint8_t **image, mlt_image_format
                if (threads == 1) {
                        sliced_proc(0, 0, 1, &desc);
                } else {
+                       threads = CLAMP(threads, 1, 16);
                        mlt_slices_run_normal(threads, sliced_proc, &desc);
                }
        }
```

**Comment by ddennedy** [comment] 2021-07-24 20:04
> The brightness filter will divide the image up into as many slices as there are threads.

Most usages of mlt_slices do this when the thread count is not explicit on the filter instance. Do you think we should limit slice count across all of mlt_slices?

**Comment by bmatherly** [comment] 2021-07-24 20:58
> Do you think we should limit slice count across all of mlt_slices?

Maybe as a temporary work-around. But in general, thread counts are going to go up and we should aspire to use as many as we can. Ideally, a developer would be thinking about practical thread usage when designing a service and would put reasonable limits in on a service-by-service basis.

Also, I expect that when frame-parallel processing is being used, the slices could be divided among all frames. For example, if we limit mlt_slices to 16 threads, but then 8 frames are using the brightness filter in parallel, then each frame would only get 2 threads in practice - even on a machine with 64 threads.

Maybe a compromise would be to put a limit in mlt_slices_run so that mlt_slices will always create the maximum number of threads, but a specific all to mlt_slices_run would be limited to a subset. It would require multiple parallel calls to mlt_slices_run to utilize all the available threads. But then the problem is what number to pick. Maybe a service will crash with 8 threads. Will we then limit everyone to a limit of 8?

**Comment by ydesgagn** [comment] 2021-07-25 12:01
One more information that can help you.

We output in 3 different resolutions. 768x432, 1280x720 and 1920x1080. We can reproduce this bug only when we output in 768x432 and slices are >= 30. 1280x720 and 1920x1080 are fine on the same machine and same input file except output resolution. Maybe just check the maths when 432 is divided by 36 or 72 or 96?

If we rollback to our previous configuration we do not have the issue anymore.

`
AUTO_APPEND_DATE=0
SOURCE_DIR="$INSTALL_DIR/src"
ACTION_GET_COMPILE_INSTALL=1
ACTION_GET_ONLY=0
ACTION_COMPILE_INSTALL=0
SOURCES_CLEAN=1
INSTALL_AS_ROOT=0
CREATE_STARTUP_SCRIPT=1
BUNDLE_EXTRAS=1
ENABLE_FREI0R=1
FREI0R_HEAD=0
# https://github.com/ugroupmedia/frei0r
FREI0R_REVISION=v1.7.0.3
ENABLE_SWFDEC=0
SWFDEC_HEAD=1
SWFDEC_REVISION=
ENABLE_MOVIT=1
MOVIT_HEAD=0
# https://git.sesse.net/?p=movit
MOVIT_REVISION=1.6.3
# https://github.com/anholt/libepoxy
LIBEPOXY_REVISION=1.5.4
X264_HEAD=0
# https://code.videolan.org/videolan/x264.git
X264_REVISION=d198931a63049db1f2c92d96c34904c69fde8117
X265_HEAD=0
# https://github.com/videolan/x265
X265_REVISION=3.4
LIBVPX_HEAD=0
# https://chromium.googlesource.com/webm/libvpx.git
LIBVPX_REVISION=v1.9.0
ENABLE_LAME=1
FFMPEG_PROJECT="FFmpeg"
FFMPEG_HEAD=0
# https://github.com/FFmpeg/FFmpeg
FFMPEG_REVISION=n4.3.1
FFMPEG_SUPPORT_H264=1
FFMPEG_SUPPORT_H265=1
FFMPEG_SUPPORT_LIBVPX=1
FFMPEG_SUPPORT_THEORA=1
FFMPEG_SUPPORT_MP3=1
FFMPEG_SUPPORT_FAAC=1
FFMPEG_SUPPORT_SSL=0
FFMPEG_ADDITIONAL_OPTIONS=
ENABLE_VIDSTAB=1
VIDSTAB_HEAD=0
# https://github.com/georgmartius/vid.stab
VIDSTAB_REVISION=v1.1.0
MLT_HEAD=0
# https://github.com/mltframework/mlt
MLT_REVISION=v6.24.0
ENABLE_WEBVFX=0
WEBVFX_HEAD=0
# https://github.com/mltframework/webvfx
WEBVFX_REVISION=1.2.0
ENABLE_RUBBERBAND=0
RUBBERBAND_HEAD=0
# https://github.com/breakfastquay/rubberband
RUBBERBAND_REVISION=v1.9
# QT_INCLUDE_DIR="$(pkg-config --variable=prefix QtCore)/include"
QT_INCLUDE_DIR=
# QT_LIB_DIR="$(pkg-config --variable=prefix QtCore)/lib"
QT_LIB_DIR=
MLT_DISABLE_SOX=0
MLT_DISABLE_SDL=0
MLT_SWIG_LANGUAGES="python"
`

We did not try the patch above but we will on Monday.

**Comment by ydesgagn** [comment] 2021-07-25 16:50
I confirm the workaround above is actually working. But the total render time is now 64s instead of 16s (when slices are limited to 29).

Can this be the issue?

```
diff --git a/mlt-6.24.0/src/modules/core/filter_brightness.c b/mlt-6.26.1/src/modules/core/filter_brightness.c
index c339fe0..8f43f0f 100644
--- a/mlt-6.24.0/src/modules/core/filter_brightness.c
+++ b/mlt-6.26.1/src/modules/core/filter_brightness.c
@@ -1,6 +1,6 @@
 /*
  * filter_brightness.c -- brightness, fade, and opacity filter
- * Copyright (C) 2003-2020 Meltytech, LLC
+ * Copyright (C) 2003-2021 Meltytech, LLC
  *
  * This library is free software; you can redistribute it and/or
  * modify it under the terms of the GNU Lesser General Public
@@ -120,7 +120,7 @@ static int filter_get_image( mlt_frame frame, uint8_t **image, mlt_image_format
        if (!error) {
                int threads = mlt_properties_get_int(properties, "threads");
                threads = CLAMP(threads, 0, mlt_slices_count_normal());
-               double alpha = mlt_properties_get(properties, "alpha")? mlt_properties_anim_get_double(properties, "alpha", position, length) : 1.0;
+               double alpha = mlt_properties_get(properties, "alpha")? MIN(mlt_properties_anim_get_double(properties, "alpha", position, length), 1.0) : 1.0;
                struct sliced_desc desc = {
                        .image = *image,
                        .rgba = (*format == mlt_image_rgb24a),
```

**Comment by bmatherly** [comment] 2021-07-25 17:07
> Can this be the issue?

That change does not "jump out" at me as a problem. But it is the only change between the versions. If you are able to do a test wit that change reverted, it would be good to know the results.

**Comment by bmatherly** [comment] 2021-07-25 17:24
Although time consuming, it would be very productive to bisect the commits between those two releases to isolate the commit that caused the problem:

https://github.com/mltframework/mlt/compare/v6.24.0...v6.26.1

**Comment by bmatherly** [comment] 2021-07-27 02:40
Thanks for the update. Keep us updated as new information is revealed.

**Comment by ddennedy** [comment] 2021-07-28 22:15
I tried to reproduce this using a custom profile defined in my MLT XML, and changing the slice count in `filter_brightness.c` to 36 on my 8 CPU machine, but I could not. I tried with real_time=-16 and avformat with x264/AAC/MP4 as well.

**Comment by ydesgagn** [comment] 2021-07-30 15:37
Here is what we do to reproduce on any machine.

```
export MLT_SLICES_COUNT=64
/var/www/melt/melt test.kdenlive -consumer avformat:output.mp4 acodec=aac vcodec=libx264
```

Our test project is available here:

https://drive.google.com/file/d/1XeEx3kUD6AAQ3w70DfSUk5ZQyI1yYe0d/view?usp=sharing

With MLT_SLICES_COUNT at 29 or less everything is fine.

**Comment by bmatherly** [comment] 2021-07-31 03:37
Thanks for the test case. The project+command did not cause a failure on my 4 core test machine. Maybe it will fail for Dan.

**Comment by ydesgagn** [comment] 2021-07-31 14:04
Here is an output added in the plugin for each slice height for 768x432 image and MLT_SLICES_COUNT=30.

```
index=3 jobs=30 ctx.height=432 slice_height=15
index=7 jobs=30 ctx.height=432 slice_height=15
index=0 jobs=30 ctx.height=432 slice_height=15
index=2 jobs=30 ctx.height=432 slice_height=15
index=4 jobs=30 ctx.height=432 slice_height=15
index=8 jobs=30 ctx.height=432 slice_height=15
index=6 jobs=30 ctx.height=432 slice_height=15
index=9 jobs=30 ctx.height=432 slice_height=15
index=10 jobs=30 ctx.height=432 slice_height=15
index=5 jobs=30 ctx.height=432 slice_height=15
index=1 jobs=30 ctx.height=432 slice_height=15
index=11 jobs=30 ctx.height=432 slice_height=15
index=13 jobs=30 ctx.height=432 slice_height=15
index=12 jobs=30 ctx.height=432 slice_height=15
index=14 jobs=30 ctx.height=432 slice_height=15
index=15 jobs=30 ctx.height=432 slice_height=15
index=16 jobs=30 ctx.height=432 slice_height=15
index=17 jobs=30 ctx.height=432 slice_height=15
index=18 jobs=30 ctx.height=432 slice_height=15
index=19 jobs=30 ctx.height=432 slice_height=15
index=20 jobs=30 ctx.height=432 slice_height=15
index=22 jobs=30 ctx.height=432 slice_height=15
index=21 jobs=30 ctx.height=432 slice_height=15
index=23 jobs=30 ctx.height=432 slice_height=15
index=25 jobs=30 ctx.height=432 slice_height=15
index=26 jobs=30 ctx.height=432 slice_height=15
index=27 jobs=30 ctx.height=432 slice_height=15
index=24 jobs=30 ctx.height=432 slice_height=15
index=28 jobs=30 ctx.height=432 slice_height=12    // height of before-last slice adjusted correctly
index=29 jobs=30 ctx.height=432 slice_height=-3    // wrong last slice height !!! 
```

As we can see, the image is completely processed after slice index 28, last slice 29 must be skipped. The negative value -3 is causing the segmentation fault.

Rene is fixing it by skipping the negative slice height but this is not a real fix. He is still searching for the original maths error.

```
static int sliced_proc(int id, int index, int jobs, void* cookie)
{
	(void) id; // unused
	struct sliced_desc ctx = *((struct sliced_desc*) cookie);
	int slice_height = (ctx.height + jobs - 1) / jobs;
	int slice_offset = index * slice_height * ctx.width;
	slice_height = MIN(slice_height, ctx.height - index * slice_height);
...

static int sliced_proc(int id, int index, int jobs, void* cookie)
{
	(void) id; // unused
	struct sliced_desc ctx = *((struct sliced_desc*) cookie);
	int slice_height = (ctx.height + jobs - 1) / jobs;
	int slice_offset = index * slice_height * ctx.width;
	slice_height = MIN(slice_height, ctx.height - index * slice_height);

        // skip negative height value
        if (slice_height < 1)
            return 0;
...
```

**Comment by ddennedy** [comment] 2021-07-31 21:11
Here is the math problem around computing the height of a slice of an image:
```
slice_height = image_height / jobs
slice_height = 432 / 30
slice_height = 14.4
```
There are two options here: floor or ceiling (or some rounding, but let's keep it simple):
- A: use floor and make the last slice bigger.
- B: use ceiling and make the last slice shorter.

In`filter_brightness.c` the `jobs - 1 / jobs` thing is a ceiling. So, option B, slice_height = 15. Now, for the last slice:
```
slice_height = 15
slice_line_start = 29 * 15 = 435
slice_height = MIN(slice_height, ctx->image->height - slice_line_start)
slice_height = MIN(15, 432 - 435) = -3
```
There are a few remedies for this:
1. skip the operation if negative
1. use CLAMP instead of MIN to clamp it to zero (basically, same as skip upon negative)
1. use option A from above: slice_height = 14, and the last slice is 26

The problem with remedy 3/option A is it makes the whole operation as slow as the larger slice. The last slice is almost twice as high. That's not good! However, there is already a form of remedy 1 in the code because of the condition in the for statement: `for ( int line = 0; line < slice_height`; 0 will always be greater than -3.

Maybe there is some other place in the slice-using code that does not protect itself from a negative slice height (or width):
- not `producer_avformat.c`, it has an explicit if/return
- `transition_composite.c` looks problematic
- not `transition_luma.c`, it has a for condition
- not frei0r, it only operates on consistent slice sizes (image height is a strict multiple of slice count and height)
- `transition_affine.c` is more complicated (it rounds the slice_height) but looks like it could have a problem

The supplied test project does not use composite or affine. I also did not reproduce the bug, but I can fix the problems I found above.

**Comment by ydesgagn** [comment] 2021-08-01 13:22
On MacOS we are using the docker image ghcr.io/mltframework/mlt/melt:v6.26.1. We simply copy the test.zip to the container, connect to the container with a bash shell, unzip the file in the /tmp directory and execute the following two lines and we get the segmentation fault.

Same on our cloud instances running Ubuntu 20.04 with melt v6.24.1 built with `build-melt.sh`.

```
export MLT_SLICES_COUNT=64
melt test.kdenlive -consumer avformat:output.mp4 acodec=aac vcodec=libx264
```

I notice that the docker image is also Ubuntu 20.04. Can this be a Linux only issue if this is working for you locally (assuming you are not using Ubuntu)?

Option 1 is probably the easiest to implement and won't slow down the entire processing due to one bigger slice.

**Comment by ddennedy** [comment] 2021-08-01 17:29
I did reproduce the problem in the v6.26.1 melt image but not v7.0.1. 
BTW, you need to remove the `root` attribute of the `mlt` element in the XML to fix the errors:
```
[producer_xml] failed to load producer "/home/rene/kdenlive-tests/frbd07/0002.png"
[producer_xml] failed to load producer "/home/rene/kdenlive-tests/frbd07/magie_pouf/magie_pouf_%04d.432.png?begin=1"
[producer_xml] failed to load producer "/home/rene/kdenlive-tests/frbd07/magie_pouf/magie_pouf_%04d.432.png?begin=1"

```
Because the way this XML is written is not relocatable.

As I tried to explain, option A is already implemented, and a negative slice height already handled and skipped. However, I was looking at the git master code. Looking at v6.26.1, I see there can be a problem in the alpha channel portion of the logic. So, yeah, we can apply a fix to the v6 branch for this.

**Comment by ddennedy** [comment] 2021-08-01 19:39
This is fixed in our docker image tagged `v6`
```
ddennedy@Gamerbox-9400:~/net/media/unsorted/mlt_bug/725/test$ docker run --init -it --rm -v $PWD:/mnt -e MLT_SLICES_COUNT=64 -e LD_LIBRARY_PATH=/usr/local/lib mltframework/melt:v6 test.kdenlive -consumer avformat:/tmp/output.mp4
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
mlt_repository_init: failed to dlopen /usr/local/lib/mlt/libmltjack.so
  (/usr/local/lib/mlt/libmltjack.so: undefined symbol: filter_jackrack_init)
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
|1=-10| |2= -5| |3= -2| |4= -1| |5=  0| |6=  1| |7=  2| |8=  5| |9= 10|
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
+---------------------------------------------------------------------+
|               H = back 1 minute,  L = forward 1 minute              |
|                 h = previous frame,  l = next frame                 |
|           g = start of clip, j = next clip, k = previous clip       |
|                0 = restart, q = quit, space = play                  |
+---------------------------------------------------------------------+
[mp4 @ 0x7fdcd8000f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7fdcd8000f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7fdcd8000f40] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mp4 @ 0x7fdcd8000f40] Encoder did not produce proper pts, making some up.
Current Position:         48
```
The docker image is being updated at the moment to not require `-e LD_LIBRARY_PATH=/usr/local/lib` on the command line.

**Closed by ddennedy** 2021-08-01 19:39 UTC
