### ISSUE TITLE
mlt 6.7.0 export gif

### ISSUE THREAD

**Issue by jalowin** [mltframework/mlt#309] opened 2018-03-12 13:32 UTC
How can I export to gif animated from a mp4 file? i try in ffmpeg and it's ok but I want pass to melt a xml file and obtain a gif animated.

Thanks for all

Best regards

**Comment by ddennedy** [comment] 2018-03-12 17:24
Duplicate of #284

**Closed by ddennedy** 2018-03-12 17:24 UTC
