### ISSUE TITLE
How to avoid fontsize scaling

### ISSUE THREAD

**Issue by ck86** [mltframework/mlt#619] opened 2020-11-19 08:03 UTC
Hey guys,
we're using the dynamictext filter to display text given by a user on a video. If the text gets too long the fontsize will be scaled down instead of a line break.
Can someone give us an advice how to achieve this? :)

Thanks in advance

**Comment by ddennedy** [comment] 2020-11-20 01:43
To prevent dynamictext (or one of the text filters/producers that powers it - qtext or pango) from down-scaling the text, make the geometry very large. If you also need the background color, then you probably need to layer in a color producer with an affine filter instead. Those text services do not support word wrap, and that will not be added. However, they do support new line characters in the text. The qtext filter in the git master branch has a new `html` and `resource` properties to support rich text that does word wrap. However, it does not do variable substitution.

  - identifier: html
    title: HTML String
    type: string
    description: Render rich text from a string containing a subset of HTML 4. The only other properties that can be used with this are geometry and bgcolour. The geometry width and height defines the page or block size while its X and Y coordinates determine its position. This property has a higher priority than argument; argument is ignored if this property is set.

  - identifier: resource
    title: HTML File
    type: string
    description: Render rich text from a file containing a subset of HTML 4. The only other properties that can be used with this are geometry and bgcolour. The geometry width and height defines the page or block size while its X and Y coordinates determine its position. This property has a higher priority than both argument and html; argument and html are ignored if this property is set.

This HTML 4 subset is defined in [Qt docs](https://doc.qt.io/qt-5/richtext-html-subset.html). There will likely be a new release soon that includes this. Since this space is for bug tracking, and this is not a bug I am closing this, but you can still comment.

**Closed by ddennedy** 2020-11-20 01:43 UTC
