### ISSUE TITLE
160701 melt script segfault, wag: libmltqt.so

### ISSUE THREAD

**Issue by CarlFK** [mltframework/mlt#119] opened 2016-07-20 17:16 UTC
ubuntu xenial

shotcut-debian8-x86_64-160701.tar.bz2

this works fine:
(veyepar) juser@dhcp20:~/local/Shotcut/Shotcut.app$ bin/melt --version
melt 6.3.0
...

but trying to run from the script, segfalt 

gdb "$INSTALL_DIR/bin/melt" "$@"

```
(veyepar) juser@dhcp20:~/local/Shotcut/Shotcut.app$ ./melt 
+ readlink -f ./melt
+ CURRENT_DIR=/home/juser/local/Shotcut/Shotcut.app/melt
+ dirname /home/juser/local/Shotcut/Shotcut.app/melt
+ INSTALL_DIR=/home/juser/local/Shotcut/Shotcut.app
+ export LD_LIBRARY_PATH=/home/juser/local/Shotcut/Shotcut.app/lib:
+ export MLT_REPOSITORY=/home/juser/local/Shotcut/Shotcut.app/lib/mlt
+ export MLT_DATA=/home/juser/local/Shotcut/Shotcut.app/share/mlt
+ export MLT_PROFILES_PATH=/home/juser/local/Shotcut/Shotcut.app/share/mlt/profiles
+ export FREI0R_PATH=/home/juser/local/Shotcut/Shotcut.app/lib/frei0r-1
+ export MLT_MOVIT_PATH=/home/juser/local/Shotcut/Shotcut.app/share/movit
+ export QT_PLUGIN_PATH=/home/juser/local/Shotcut/Shotcut.app/lib/qt5
+ export QML2_IMPORT_PATH=/home/juser/local/Shotcut/Shotcut.app/lib/qml
+ gdb /home/juser/local/Shotcut/Shotcut.app/bin/melt
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/juser/local/Shotcut/Shotcut.app/bin/melt...done.
(gdb) run
Starting program: /home/juser/local/Shotcut/Shotcut.app/bin/melt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
mlt_repository_init: failed to dlopen /home/juser/local/Shotcut/Shotcut.app/lib/mlt/libmltwebvfx.so
  (libgstapp-0.10.so.0: cannot open shared object file: No such file or directory)

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000750 in ?? ()
(gdb) bt full
#0  0x0000000000000750 in ?? ()
No symbol table info available.
#1  0x00007ffff7de74ea in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffe308, env=env@entry=0x7fffffffe318)
    at dl-init.c:72
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
        init_array = <optimized out>
#2  0x00007ffff7de75fb in call_init (env=0x7fffffffe318, argv=0x7fffffffe308, 
    argc=1, l=<optimized out>) at dl-init.c:30
No locals.
#3  _dl_init (main_map=main_map@entry=0x73e950, argc=1, argv=0x7fffffffe308, 
    env=0x7fffffffe318) at dl-init.c:120
        preinit_array = <optimized out>
        preinit_array_size = <optimized out>
        i = 14
#4  0x00007ffff7dec712 in dl_open_worker (a=a@entry=0x7fffffffdec0)
    at dl-open.c:575
        args = 0x7fffffffdec0
        file = <optimized out>
        mode = <optimized out>
        call_map = <optimized out>
---Type <return> to continue, or q <return> to quit---
        dst = <optimized out>
        new = <optimized out>
        __PRETTY_FUNCTION__ = "dl_open_worker"
        r = <optimized out>
        reloc_mode = <optimized out>
        nmaps = <optimized out>
        l = <optimized out>
        maps = <optimized out>
        relocation_in_progress = <optimized out>
        any_tls = <optimized out>
        first_static_tls = <optimized out>
#5  0x00007ffff7de7394 in _dl_catch_error (
    objname=objname@entry=0x7fffffffdeb0, 
    errstring=errstring@entry=0x7fffffffdeb8, 
    mallocedp=mallocedp@entry=0x7fffffffdeaf, 
    operate=operate@entry=0x7ffff7dec300 <dl_open_worker>, 
    args=args@entry=0x7fffffffdec0) at dl-error.c:187
        errcode = 32767
        c = {objname = 0x7fffffffdeb0, errstring = 0x7fffffffdeb8, 
          malloced = 0x7fffffffdeaf, errcode = 0x7fffffffdd8c, env = {{
              __jmpbuf = {140737488347088, -7189635459537260952, 2147483650, 
                6394320, 140737349720900, 140737354125376, 
                -7189635459470152088, -7189617580821664152}, 
              __mask_was_saved = -828265453, __saved_mask = {__val = {
                  54167216, 140733193388051, 0, 140737354103376, 
                  140737488346704, 8589925972, 140737488346688, 457950612, 
                  140737349606454, 4294967295, 7598416, 140737343461712, 
                  140737353966824, 79, 140737354103376, 140737488347072}}}}}
        catchp = 0x7ffff7fd46f8
        old = <optimized out>
#6  0x00007ffff7debbd9 in _dl_open (
    file=0x6191d0 "/home/juser/local/Shotcut/Shotcut.app/lib/mlt/libmltqt.so", 
mode=-2147483646, caller_dlopen=0x7ffff7bc9b44 <mlt_repository_init+292>, 
    nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x7fffffffe318)
    at dl-open.c:660
        args = {
          file = 0x6191d0 "/home/juser/local/Shotcut/Shotcut.app/lib/mlt/libmltqt.so", mode = -2147483646, 
          caller_dlopen = 0x7ffff7bc9b44 <mlt_repository_init+292>, 
          caller_dl_open = 0x7ffff73bdf09 <dlopen_doit+89>, map = 0x73e950, 
          nsid = 0, argc = 1, argv = 0x7fffffffe308, env = 0x7fffffffe318}
        objname = 0x1 <error: Cannot access memory at address 0x1>
        errstring = 0x7ffff7dd6c10 <vfprintf@got.plt> "0\341`\367\377\177"
        malloced = false
        errcode = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_open"
#7  0x00007ffff73bdf09 in dlopen_doit (a=a@entry=0x7fffffffe0f0)
    at dlopen.c:66
        args = 0x7fffffffe0f0
#8  0x00007ffff7de7394 in _dl_catch_error (objname=0x60f670, 
    errstring=0x60f678, mallocedp=0x60f668, 
    operate=0x7ffff73bdeb0 <dlopen_doit>, args=0x7fffffffe0f0)
    at dl-error.c:187
        errcode = 32767
        c = {objname = 0x60f670, errstring = 0x60f678, malloced = 0x60f668, 
          errcode = 0x7fffffffdfcc, env = {{__jmpbuf = {0, 
                -7189617283225178520, 140737488347376, 22, 6353584, 0, 
                -7189635459562426776, -7189617580821664152}, 
              __mask_was_saved = 25, __saved_mask = {__val = {
                  140737349727746, 255, 6354528, 140737341284016, 
                  140737488347376, 22, 6353584, 0, 140737343933116, 6394080, 
                  140737343974195, 0, 46, 18446744073709551612, 6354528, 
                  140737341284016}}}}}
        catchp = 0x7ffff7fd46f8
---Type <return> to continue, or q <return> to quit---
        old = <optimized out>
#9  0x00007ffff73be571 in _dlerror_run (
    operate=operate@entry=0x7ffff73bdeb0 <dlopen_doit>, 
    args=args@entry=0x7fffffffe0f0) at dlerror.c:163
        result = 0x60f660
#10 0x00007ffff73bdfa1 in __dlopen (file=<optimized out>, 
    mode=<optimized out>) at dlopen.c:87
        args = {
          file = 0x6191d0 "/home/juser/local/Shotcut/Shotcut.app/lib/mlt/libmltqt.so", mode = 2, new = 0x16, 
          caller = 0x7ffff7bc9b44 <mlt_repository_init+292>}
#11 0x00007ffff7bc9b44 in mlt_repository_init (
    directory=0x1 <error: Cannot access memory at address 0x1>)
    at mlt_repository.c:105
        flags = -7416
        object_name = 0x6191d0 "/home/juser/local/Shotcut/Shotcut.app/lib/mlt/libmltqt.so"
        object = 0x0
        self = 0x60e020
        dir = 0x60f2b0
        i = 25
        plugin_count = 22
        __FUNCTION__ = "mlt_repository_init"
#12 0x00007ffff7bc9378 in mlt_factory_init (
    directory=0x7fffffffe687 "/home/juser/local/Shotcut/Shotcut.app/lib/mlt", 
    directory@entry=0x0) at mlt_factory.c:184
No locals.
#13 0x000000000040229c in main (argc=1, argv=0x7fffffffe308) at melt.c:718
        i = <optimized out>
        consumer = 0x0
        store = 0x0
        name = 0x0
        profile = 0x0
        is_progress = 0
        is_silent = 0
        is_abort = 0
        is_getc = 0
        error = 0
        backup_profile = <optimized out>
        repo = <optimized out>
(gdb) 
```

**Comment by ddennedy** [comment] 2016-07-20 18:30
Duplicate of https://github.com/mltframework/shotcut/issues/269
From your output see ` (libgstapp-0.10.so.0: cannot open shared object file: No such file or directory)`.
Shotcut builds are currently incompatible with Ubuntu Xenial and Debian unstable due to using Qt 5.1, which has a dependency on gstreamer 0.10. But this is not a bug in MLT; just the build you are using.

**Closed by ddennedy** 2016-07-20 18:30 UTC
