### ISSUE TITLE
melt video playback not working

### ISSUE THREAD

**Issue by paperbenni** [mltframework/mlt#480] opened 2019-10-03 15:43 UTC
Specifying a consumer like avformat works, but the default sdl one shows up as an empty window. audio playback works. 
WM is dwm
OS: Arch
GTX 1060 proprietary drivers
ryzen 1700
I tried killing the compositor, no difference. 
sdl is installed, melt from the arch repo.

**Comment by ddennedy** [comment] 2019-10-03 22:56
duplicate of #449

**Closed by ddennedy** 2019-10-03 22:56 UTC

**Comment by ddennedy** [comment] 2023-09-20 19:38
Fixed in cb0ff75
