### ISSUE TITLE
libmltsdl.so: undefined symbol: XGetWindowAttributes

### ISSUE THREAD

**Issue by mantielero** [mltframework/mlt#748] opened 2021-11-07 16:07 UTC
I am a newbie trying to compile a simple example, but I am getting this error in ArchLinux.

I have tried with both ArchLinux's `mlt` and `mlt-git` packages.

When I try [play.cpp](https://github.com/mltframework/mlt/blob/master/src/examples/play.cpp) example I get the error:
```
$ ./play video.mp4
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltsdl.so
  (/usr/lib/mlt-7/libmltsdl.so: undefined symbol: XGetWindowAttributes)
Violación de segmento (`core' generado)
```
> Meaning: segmet violation ("core" generated)

kdenlive works fine on my system.

------

I have tried as well using plain C. I tried with the following code:
```c
// gcc ex.c -o ex -I/usr/include/mlt-7 -l mlt-7 
#include <stdio.h>
#include <unistd.h>
#include <framework/mlt.h>

int main( int argc, char *argv[] )
{
    // Initialise the factory
    if ( mlt_factory_init( NULL ) == 0 )
    {
        // Create the default consumer
        mlt_consumer hello = mlt_factory_consumer( NULL, "sdl2", NULL );

        // Create via the default producer
        mlt_producer world = mlt_factory_producer( NULL, "color", "red" );

        // Connect the producer to the consumer
        mlt_consumer_connect( hello, mlt_producer_service( world ) );

        // Start the consumer
        mlt_consumer_start( hello );

        // Wait for the consumer to terminate
        while( !mlt_consumer_is_stopped( hello ) )
            sleep( 1 );

        // Close the consumer
        mlt_consumer_close( hello );

        // Close the producer
        mlt_producer_close( world );

        // Close the factory
        mlt_factory_close( );
    }
    else
    {
        // Report an error during initialisation
        fprintf( stderr, "Unable to locate factory modules\n" );
    }

    // End of program
    return 0;
}
``` 

When I run it:
```bash
$ ./ex
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltsdl.so
  (/usr/lib/mlt-7/libmltsdl.so: undefined symbol: XGetWindowAttributes)
Unable to locate factory modules
```

**Comment by bmatherly** [comment] 2021-11-08 01:36
>   (/usr/lib/mlt-7/libmltsdl.so: undefined symbol: XGetWindowAttributes)

XGetWindowAttributes is provided by Xlib. Do you have libX11 installed?

**Comment by mantielero** [comment] 2021-11-08 18:13
I have tested the following code:
```c
#include <X11/Xlib.h>
#include <stdio.h>
#include <stdlib.h>

/*
Returns the parent window of "window" (i.e. the ancestor of window
that is a direct child of the root, or window itself if it is a direct child).
If window is the root window, returns window.
*/
Window get_toplevel_parent(Display * display, Window window)
{
     Window parent;
     Window root;
     Window * children;
     unsigned int num_children;

     while (1) {
         if (0 == XQueryTree(display, window, &root,
                   &parent, &children, &num_children)) {
             fprintf(stderr, "XQueryTree error\n");
             abort(); //change to whatever error handling you prefer
         }
         if (children) { //must test for null
             XFree(children);
         }
         if (window == root || parent == root) {
             return window;
         }
         else {
             window = parent;
         }
     }
}

int main(int argc, char *argv[])
{
    Display *display;
    Window focus, toplevel_parent_of_focus;
    XWindowAttributes attr;
    int revert;

    display = XOpenDisplay(NULL);
    XGetInputFocus(display, &focus, &revert);
    toplevel_parent_of_focus = get_toplevel_parent(display, focus);
    XGetWindowAttributes(display, toplevel_parent_of_focus, &attr);
    printf("[0x%x] %d x %d\n", (unsigned)toplevel_parent_of_focus, 
       attr.width, attr.height);

    return 0;
}
```
and compiled with:
```bash
$ gcc b.c -o b -lX11
$ ./b
[0x280000a] 708 x 1024
```

**Comment by mantielero** [comment] 2021-11-08 18:21
OK. It looks like the issue was that I was compiling:
```bash
$ gcc ex.c -o ex -I/usr/include/mlt-7 -l mlt-7
```
while I should do:
```bash
$ gcc ex.c -o ex -I/usr/include/mlt-7 -lX11 -lmlt-7 
```

**Comment by antonio-rojas** [comment] 2021-11-09 17:17
This is an actual mlt bug. The sdl module uses Xlib functions:

https://github.com/mltframework/mlt/blob/master/src/modules/sdl/consumer_sdl.c#L943

but doesn't link to X11 when built with cmake:

https://github.com/mltframework/mlt/blob/master/src/modules/sdl/CMakeLists.txt#L11

The old autotools build system did link to it:

https://github.com/mltframework/mlt/blob/v6.26.1/src/modules/sdl/Makefile#L26

**Comment by mantielero** [comment] 2021-11-09 18:17
I have tried adding `X11` to the `CMakeLists.txt` file (L11) and building it locally. 

When I run `melt somevideo.mp4`, the error related to `libmltsdl.so` disappears, but I continue to get a black screen despite the audio is there.

**Comment by ddennedy** [comment] 2021-11-09 19:27
> This is an actual mlt bug. The sdl module uses Xlib functions:

The build uses pkg-config, and maybe the SDL package is under-specifying its libs. It is incorrect to assume all platforms use X. However, really, this module is also deprecated in favor of the sdl2 module. We do not link any extra libs for the sdl2 module either, `pkg-config --libs sdl2` does not report any extra libs, and yet melt with the sdl2 consumer runs fine for me on Linux, macOS, and Windows (and `melt/CMakeLists.txt` does not link any extra libs either). So, it is a SDL 1.2 build problem in my opinion.

> I continue to get a black screen despite the audio is there.

That is a duplicate of #449. There is no fix for it. I think it affects Linux systems with nvidia graphics, but I could be wrong. You can try to fix it yourself or use a different consumer.

**Comment by antonio-rojas** [comment] 2021-11-09 19:38
> The build uses pkg-config, and maybe the SDL package is under-specifying its libs. It is incorrect to assume all platforms use X. 

This has nothing to do with SDL: It's MLT which is using X11 code directly in the SDL module, so it should link to X11 itself (conditionally on the needed platforms), instead of relying on it being transitively linked via other dependencies. This is what was done in the autotools build.

> We do not link any extra libs for the sdl2 module either, `pkg-config --libs sdl2` does not report any extra libs, and yet melt with the sdl2 consumer runs fine for me on Linux, macOS, and Windows (and `melt/CMakeLists.txt` does not link any extra libs either). 

The sdl2 module doesn't use any X11 code as far as I can see, so the problem doesn't apply.

**Comment by ddennedy** [comment] 2021-11-09 19:49
> It's MLT which is using X11 code directly in the SDL module

Oh, yes, I found it:
https://github.com/mltframework/mlt/blob/master/src/modules/sdl/consumer_sdl_still.c#L613

I had checked the includes of `consumer_sdl.c` only before. I am working on a change for this. 
```
--- src/modules/sdl/CMakeLists.txt
+++ src/modules/sdl/CMakeLists.txt
@@ -11,4 +11,12 @@ target_compile_options(mltsdl PRIVATE ${MLT_COMPILE_OPTIONS})
 target_link_libraries(mltsdl PRIVATE mlt m Threads::Threads PkgConfig::sdl)
 
+if(NOT WIN32)
+  if (APPLE)
+    target_link_libraries(mltsdl PRIVATE objc "-framework Foundation")
+  else()
+    target_link_libraries(mltsdl PRIVATE X11)
+  endif()
+endif()
+
 set_target_properties(mltsdl PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${MLT_MODULE_OUTPUT_DIRECTORY}")
 
```

**Closed** 2021-11-09 19:53 UTC
