### ISSUE TITLE
Cropped FLAC produces audio artifacts (crackles, pops) 

### ISSUE THREAD

**Issue by tuffnerdstuff** [mltframework/mlt#741] opened 2021-10-15 15:03 UTC
### Description
When rendering an MLT file referencing a FLAC audio file, the rendered output will contain audible artifacts (crackles, pops) if the producers in offset is greater than zero (beginning is cropped), otherwise the audio is clean.

### Reproduction
1. Generate a 2 second sine wave FLAC audio using ffmpeg: `ffmpeg -f lavfi -i "sine=frequency=1000:duration=2" sine.flac`
2. Render a WAV 0 seconds in (duration 2 seconds): `melt -profile atsc_1080p_60 sine.flac in=00:00:00.000 out=00:00:02.000 -consumer avformat:sine_clean.wav`
3. Render a WAV 1 second in (duration 1 second): `melt -profile atsc_1080p_60 sine.flac in=00:00:01.000 out=00:00:02.000 -consumer avformat:sine_crackle.wav`

You will notice that sine_clean.wav is fine, while sine_crackle.wav is distorted.

### Workaround
If you use uncompressed WAV audio instead of FLAC there are no issues whatsoever.

### Technical Info
* MLT version: `7.0.1`
* FFmpeg version: `n4.4`
* OS: `5.10.68-1-MANJARO #1 SMP PREEMPT Wed Sep 22 12:29:47 UTC 2021 x86_64 GNU/Linux`

### Additional Info
I also tried different FLAC bit-depths (16 and 24 bit) as well as sampling-rates (44,1kHz and 48kHz), but the problem stays the same. If I do the same using ffmpeg, there is no distortion:
`ffmpeg -i sine.flac -ss 00:00:01.000 sine_ffmpeg.wav`

**Comment by tuffnerdstuff** [comment] 2021-10-15 16:46
Thanks for the quick reply! I will try using FLAC in a container (e.g. Matroska) and report back if I find another workaround. I'll also try to reproduce the problem using FFmpeg only. Is there a way to somehow log what MLT inputs into FFmpeg?

**Comment by frdbr** [comment] 2021-10-15 21:19
In Kdenlive we've noticed crackles/pops when using 60fps projects. It doesn't happen with 24/30 fps though... Don't know if this is relevant but hope it helps find a fix:  

https://bugs.kde.org/show_bug.cgi?id=410726

**Comment by ddennedy** [comment] 2021-10-15 21:33
@frdbr The problem with the kdenlive bug you reference is that it is more about general audio distortions, many of which have been fixed or significantly improved, while this is specifically about FLAC as a source.

**Comment by evertvorster** [comment] 2023-03-06 12:46
I have run into this bug now, and it's really reproducable. 

Using 60fps video, I export the audio as a wav file, and edit in Audacity. From there the audio is exported as a .flac file, and imported back into Kdenlive. The beginning and end of the file is corpped. 

I did not notice this bug while using 25fps, but once I started working in 60fps it is definitely there. 
When I export the audio as mp3 from audacity, and replace the clip in kdenlive, there is no audio crackling. 

If I play the exported .flac file in another application, there is no crackling either.

**Comment by bmatherly** [comment] 2023-03-08 13:35
Simple steps to reproduce from @j-b-m:

Ok, so using the sample sine wav file provided in the Kdenlive bug report:
[sine.flac](https://bugs.kde.org/attachment.cgi?id=119989)

The problem can be reproduced using this melt command:
melt -profile atsc_1080p_60 sine.flac in=735 -consumer avformat:test1.wav

The resulting file has clear audio cracks at start. Using an atsc_1080p_25 profile I didn't get audio cracks

**Comment by tuffnerdstuff** [comment] 2023-03-08 15:07
Thanks for the shortened setup @bmatherly ! It did not work for my setup with the sine generated via ffmpeg, but I adapted your approach and I will update my instructions.

**Comment by bmatherly** [comment] 2023-03-09 04:07
I have a proposed fix for this specific FLAC issue. Can someone please test this proposed change with their own test case?

```
diff --git a/src/modules/avformat/producer_avformat.c b/src/modules/avformat/producer_avformat.c
index 9e8a63df..d3e2188d 100644
--- a/src/modules/avformat/producer_avformat.c
+++ b/src/modules/avformat/producer_avformat.c
@@ -2792,9 +2792,10 @@ static int decode_audio( producer_avformat self, int *ignore, const AVPacket *pk
                if ( self->seekable || int_position > 0 )
                {
                        int64_t ahead_threshold = 2;
-                       if ( codec_context->codec_id == AV_CODEC_ID_WMAPRO )
+                       if ( codec_context->codec_id == AV_CODEC_ID_WMAPRO ||
+                                codec_context->codec_id == AV_CODEC_ID_FLAC )
                        {
-                               // WMAPro needs more tolerance for sync detection
+                               // Some codecs needs more tolerance for sync detection
                                ahead_threshold = 4;
                        }
 

```

**Comment by bmatherly** [comment] 2023-03-10 04:06
Thanks for your testing. I think that 8 frames of tolerance is too much - it would make the lip sync be off for lower frame rates. I think I see that the problem is the PTS offset calculation does not account for samples already in the buffer. And FLAC frames are very large - leaving many samples in the buffer. Here is another proposed fix. I hope you can continue to help me keep testing.

```
diff --git a/src/modules/avformat/producer_avformat.c b/src/modules/avformat/producer_avformat.c
index 9e8a63df..7449c5aa 100644
--- a/src/modules/avformat/producer_avformat.c
+++ b/src/modules/avformat/producer_avformat.c
@@ -2705,6 +2705,7 @@ static int decode_audio( producer_avformat self, int *ignore, const AVPacket *pk
 
        int channels = codec_context->channels;
        int audio_used = self->audio_used[ index ];
+       int audio_used_at_start = audio_used;
        int ret = 0;
        int discarded = 1;
        int sizeof_sample = sample_bytes( codec_context );
@@ -2763,6 +2764,7 @@ static int decode_audio( producer_avformat self, int *ignore, const AVPacket *pk
                int n = FFMIN( audio_used, *ignore );
                *ignore -= n;
                audio_used -= n;
+               audio_used_at_start -= n;
                memmove( audio_buffer, &audio_buffer[ n * channels * sizeof_sample ],
                                 audio_used * channels * sizeof_sample );
        }
@@ -2771,7 +2773,9 @@ static int decode_audio( producer_avformat self, int *ignore, const AVPacket *pk
        // Skip this on non-seekable, audio-only inputs.
        if ( !discarded && pkt->pts >= 0 && ( self->seekable || self->video_format ) && *ignore == 0 && audio_used > samples / 2 )
        {
-               int64_t pts = pkt->pts;
+               double timebase = av_q2d( context->streams[ index ]->time_base );
+               int64_t pts_offset = lrint((double)audio_used_at_start / timebase / (double)codec_context->sample_rate);
+               int64_t pts = pkt->pts - pts_offset;
                if ( self->first_pts != AV_NOPTS_VALUE )
                        pts -= av_rescale_q(self->first_pts,
                                                                context->streams[self->video_index]->time_base,
@@ -2780,7 +2784,6 @@ static int decode_audio( producer_avformat self, int *ignore, const AVPacket *pk
                        pts -= av_rescale_q(context->start_time,
                                                                AV_TIME_BASE_Q,
                                                                context->streams[ index ]->time_base);
-               double timebase = av_q2d( context->streams[ index ]->time_base );
                int64_t int_position = llrint( timebase * pts * fps );
                int64_t req_position = llrint( timecode * fps );
                int64_t req_pts =      llrint( timecode / timebase );
```

**Comment by bmatherly** [comment] 2023-03-10 12:49
Here you go: https://github.com/mltframework/mlt/pull/885

**Comment by tuffnerdstuff** [comment] 2023-03-10 19:47
Thanks for pushing the branch @bmatherly! I tested your fix and the audio is crystal clear now :+1:

**Comment by evertvorster** [comment] 2023-03-13 18:10
Just tested here, and for me there is also no more popping noises when using FLAC.

**Comment by bmatherly** [comment] 2023-03-13 23:06
Thanks for testing. In addition to the FLAC issue, we have a high concern about regression with other formats. If you are willing, it would be very helpful if you could help us test other formats.

For example:
1) Put a clip on the timeline
2) Snip the clips at various places
3) Play the timeline - does it sound the same as the currently released version?

**Closed** 2023-03-16 06:25 UTC

**Comment by tuffnerdstuff** [comment] 2023-03-16 12:11
Thanks @bmatherly and @ddennedy for putting so much effort in fixing this issue!
